### ISSUE TITLE
HDD not spinning down

### ISSUE THREAD

**Issue by mindrunner** [syncthing/syncthing-inotify#104]
I observed a weird behaviour with syncthing-inotify. When enabled, one of the HDDs is not spinning down. (Set to standby after 30 Minutes)  Syncthing's rescan interval is set to 0 and without syncthing-inotify all disks are going to standby. I do not really know where to start investigating. Any hints?

**Comment by Zillode** [comment]
How big is your folder in terms of disk size and number of files?

**Comment by mindrunner** [comment]
About 700GB / 200.000 Files.

**Comment by Zillode** [comment]
You can increase the verbosity level and see what's happening using the cmd `syncthing-inotify -verbosity=4`.

**Comment by mindrunner** [comment]
This happens every hour:

> [TRACE] 13:19:33 Requesting STEvents: 8545
[TRACE] 13:20:33 Requesting STEvents: 8546
[TRACE] 13:21:33 Requesting STEvents: 8547
[TRACE] 13:22:33 Requesting STEvents: 8548
[TRACE] 13:23:33 Requesting STEvents: 8549
[TRACE] 13:24:33 Requesting STEvents: 8550
[TRACE] 13:25:33 Requesting STEvents: 8551
[TRACE] 13:26:27 Asking to delay full scanning of gentoo
[TRACE] 13:26:27 Informing ST: gentoo: [.stfolder]
[TRACE] 13:26:27 Requesting STEvents: 8552
[OK] 13:26:27 Syncthing is indexing change in gentoo: [.stfolder]
[TRACE] 13:26:27 Requesting STEvents: 8553
[TRACE] 13:26:28 Asking to delay full scanning of drive
[TRACE] 13:26:28 Informing ST: drive: [.stfolder]
[OK] 13:26:28 Syncthing is indexing change in drive: [.stfolder]
[TRACE] 13:26:28 Requesting STEvents: 8554
[TRACE] 13:26:28 Requesting STEvents: 8555
[TRACE] 13:26:33 Requesting STEvents: 8556
[TRACE] 13:27:33 Requesting STEvents: 8557
[TRACE] 13:28:33 Requesting STEvents: 8558
[TRACE] 13:29:33 Requesting STEvents: 8559
[TRACE] 13:30:33 Requesting STEvents: 8560
[TRACE] 13:31:33 Requesting STEvents: 8561
[TRACE] 13:32:33 Requesting STEvents: 8562
[TRACE] 13:33:33 Requesting STEvents: 8563
[TRACE] 13:34:33 Requesting STEvents: 8564
[TRACE] 13:35:33 Requesting STEvents: 8565
[TRACE] 13:36:33 Requesting STEvents: 8566
[TRACE] 13:37:33 Requesting STEvents: 8567
[TRACE] 13:38:33 Requesting STEvents: 8568
[TRACE] 13:39:33 Requesting STEvents: 8569
[TRACE] 13:40:33 Requesting STEvents: 8570
[TRACE] 13:41:33 Requesting STEvents: 8571
[TRACE] 13:42:33 Requesting STEvents: 8572
[TRACE] 13:43:33 Requesting STEvents: 8573
[TRACE] 13:44:33 Requesting STEvents: 8574
[TRACE] 13:45:33 Requesting STEvents: 8575
[TRACE] 13:46:33 Requesting STEvents: 8576
[TRACE] 13:47:33 Requesting STEvents: 8577
[TRACE] 13:48:33 Requesting STEvents: 8578
[TRACE] 13:49:33 Requesting STEvents: 8579
[TRACE] 13:50:33 Requesting STEvents: 8580
[TRACE] 13:51:33 Requesting STEvents: 8581
[TRACE] 13:52:33 Requesting STEvents: 8582
[TRACE] 13:53:33 Requesting STEvents: 8583
[TRACE] 13:54:33 Requesting STEvents: 8584
[TRACE] 13:55:33 Requesting STEvents: 8585
[TRACE] 13:56:33 Requesting STEvents: 8586
[TRACE] 13:57:33 Requesting STEvents: 8587
[TRACE] 13:58:33 Requesting STEvents: 8588
[TRACE] 13:59:33 Requesting STEvents: 8589
[TRACE] 14:00:33 Requesting STEvents: 8590
[TRACE] 14:01:33 Requesting STEvents: 8591
[TRACE] 14:02:33 Requesting STEvents: 8592
[TRACE] 14:03:33 Requesting STEvents: 8593
[TRACE] 14:04:33 Requesting STEvents: 8594
[TRACE] 14:05:33 Requesting STEvents: 8595
[TRACE] 14:06:33 Requesting STEvents: 8596
[TRACE] 14:07:33 Requesting STEvents: 8597
[TRACE] 14:08:33 Requesting STEvents: 8598
[TRACE] 14:09:33 Requesting STEvents: 8599
[TRACE] 14:10:33 Requesting STEvents: 8600
[TRACE] 14:11:33 Requesting STEvents: 8601
[TRACE] 14:12:33 Requesting STEvents: 8602
[TRACE] 14:13:33 Requesting STEvents: 8603
[TRACE] 14:14:33 Requesting STEvents: 8604
[TRACE] 14:15:33 Requesting STEvents: 8605
[TRACE] 14:16:33 Requesting STEvents: 8606
[TRACE] 14:17:33 Requesting STEvents: 8607
[TRACE] 14:18:33 Requesting STEvents: 8608
[TRACE] 14:19:33 Requesting STEvents: 8609
[TRACE] 14:20:33 Requesting STEvents: 8610
[TRACE] 14:21:33 Requesting STEvents: 8611
[TRACE] 14:22:33 Requesting STEvents: 8612
[TRACE] 14:23:33 Requesting STEvents: 8613
[TRACE] 14:24:33 Requesting STEvents: 8614
[TRACE] 14:25:33 Requesting STEvents: 8615
[TRACE] 14:26:22 Asking to delay full scanning of gentoo
[TRACE] 14:26:22 Informing ST: gentoo: [.stfolder]
[TRACE] 14:26:22 Requesting STEvents: 8616
[OK] 14:26:22 Syncthing is indexing change in gentoo: [.stfolder]
[TRACE] 14:26:22 Requesting STEvents: 8617
[TRACE] 14:26:23 Asking to delay full scanning of drive
[TRACE] 14:26:23 Informing ST: drive: [.stfolder]
[OK] 14:26:23 Syncthing is indexing change in drive: [.stfolder]
[TRACE] 14:26:23 Requesting STEvents: 8618
[TRACE] 14:26:23 Requesting STEvents: 8619
[TRACE] 14:26:33 Requesting STEvents: 8620
[TRACE] 14:27:33 Requesting STEvents: 8621
[TRACE] 14:28:33 Requesting STEvents: 8622

**Comment by calmh** [comment]
This

```
[TRACE] 13:26:27 Asking to delay full scanning of gentoo
[TRACE] 13:26:27 Informing ST: gentoo: [.stfolder]
[TRACE] 13:26:27 Requesting STEvents: 8552
[OK] 13:26:27 Syncthing is indexing change in gentoo: [.stfolder]
```

will cause Syncthing to run the folder health check. Compare (different but relevant) https://github.com/syncthing/syncthing/issues/2497.

**Comment by Zillode** [comment]
Thanks for reporting. I'll close it because it needs to be fixed upstream
