### ISSUE TITLE
Testing failed

### ISSUE THREAD

**Issue by favonia** [syncthing/syncthing-inotify#105]
Currently the testing is failing with the following message on my machine:

```
panic: close of closed channel

goroutine 13 [running]:
panic(0x74aaa0, 0xc820067d20)
	/usr/lib/go/src/runtime/panic.go:481 +0x3e6
github.com/syncthing/syncthing-inotify.TestFilesAggregation.func1(0x86b1c0, 0x5, 0xc820067c90, 0x1, 0x1, 0x0, 0x0)
	/tmp/syncthing-inotify-git/github.com/syncthing/syncthing-inotify/syncwatcher_test.go:427 +0x2dd
github.com/syncthing/syncthing-inotify.accumulateChanges(0x2faf080, 0x86b1c0, 0x5, 0xc82008af06, 0x5, 0x33, 0xc820064720, 0xc820064780, 0xc820011350, 0x9)
	/tmp/syncthing-inotify-git/github.com/syncthing/syncthing-inotify/syncwatcher.go:759 +0x1ce3
created by github.com/syncthing/syncthing-inotify.TestFilesAggregation
	/tmp/syncthing-inotify-git/github.com/syncthing/syncthing-inotify/syncwatcher_test.go:430 +0x3a2
exit status 2
FAIL	github.com/syncthing/syncthing-inotify	7.113s
```

**Comment by Zillode** [comment]
What kind of machine are you using? (OS, CPU, ...)
Maybe you need to increase the timeout, see `testDebounceTimeout := 50 * time.Millisecond`

**Comment by favonia** [comment]
@Zillode I am running an almost unmodified Linux kernel 4.6rc6 and Go 1.6.2 on an x64 CPU. I am using Arch Linux so almost everything is of the latest stable version. The files were compiled and tested on a RAM disk. I indeed finally reached ``PASS`` after increasing the ``50`` to ``500`` and running it repeatedly. There were other potentially failing tests but they do not fail as often as the particular test I mentioned above (I did not change the number ``50`` in all tests except the above one):

```
--- FAIL: TestFilesAggregation (0.75s)
	syncwatcher_test.go:421: Invalid result for directory change: (test1) []string{"a/0", "a/1", "a/10", "a/11", "a/12", "a/13", "a/14", "a/15", "a/16", "a/17", "a/18", "a/19", "a/2", "a/20", "a/21", "a/22", "a/23", "a/24", "a/25", "a/26", "a/27", "a/28", "a/29", "a/3", "a/30", "a/32", "a/33", "a/34", "a/37", "a/38", "a/39", "a/4", "a/40", "a/42", "a/43", "a/45", "a/46", "a/48", "a/5", "a/6", "a/7", "a/8", "a/9"}
```

```
--- FAIL: TestSTEvents (2.50s)
	syncwatcher_test.go:384: Invalid result for directory change: (test1) []string{"file2"}
	syncwatcher_test.go:398: Callback not correctly triggered
```

I am more than happy to hack more but unfortunately not familiar with Go and the trigger logic.

**Comment by Zillode** [comment]
The timeout values are a trade-off between quick testing and getting it working on slower machines machines. I'll increase the timeouts in a future commit, thanks.

**Comment by favonia** [comment]
I can't believe a RAM disk with a Skylake core is classified as "slow". There are not many faster combinations out there. I'd rather believe there's some ``inotify`` bug in Linux 4.6rc6. Anyways, if it's indeed about the speed, could we dynamically determine the threshold?

**Comment by favonia** [comment]
@Zillode I am testing on a RAM disk with a Skylake core. It is hard for me to believe that my machine is "slower". Could there be other causes? Also, I am wondering if we can dynamically determine a threshold from successful operations.

**Comment by Zillode** [comment]
That is indeed quite odd, but I wouldn't worry too much as it is fixed by increasing the timeout value.

The timeout is used for two reasons:
1. We ensure the test fails if we don't get answers in time (this is what you experience imo)
2. We ensure no additional (unexpected) results get pushed from the same accumulation after we retrieved all events.

**Comment by favonia** [comment]
What I am suggesting is to measure the time for a successful operation in the beginning, and then we wait for twice or thrice as much as the measured time for all following testing. A more advanced way is to use all successful operations to get averages and deviations but that is overkilling I think. This way the test is fast on faster machine but still working on slower machines.

By the way, I tried this on a RAM disk with a much weaker and older CPU/chipsets and it passed at the first time. Very strange.
