### ISSUE TITLE
Relative paths no longer sync instantly

### ISSUE THREAD

**Issue by a-m-s** [syncthing/syncthing-inotify#108]
I just updated syncthing to 0.13.1 and discovered that my file edits weren't getting synced instantly any more.

I see the syncthing-inotify log shows that it did see the file event, and the Syncthing UI shows a scan happening at the appropriate moment, but the file changes do not get synced.

The problem appears to be that I had the sync folder specified as a path relative to my home directory (i.e. with no leading '/'), but the syncthing-inotify logs show an absolute path.

I've now removed the folder sync with the relative path, and replaced it with an otherwise identical configuration using an absolute path, and everything is working smoothly again.

I suspect that either syncthing-inotify needs to modify the path it passes to syncthing, or syncthing needs to recognise that relative and absolute paths can match.

**Comment by calmh** [comment]
I think syncthing, in the API, always speaks paths relative to the folder root and this shouldn't have changed in 0.13...
