### ISSUE TITLE
Windows 7 x64 : Deletes not detected

### ISSUE THREAD

**Issue by meztup** [syncthing/syncthing-inotify#109]
Windows 7 x64 / Syncthing 0.13.2 / iNotify 0.8:

New and modified files/folders are detected and synced immediately. However, file/folder deletes are not synced. One must manually "force" a refresh from the Syncthing GUI. Its possible that this is an issue with Syncthing rather than iNotify.
 
EDIT: After further testing, it appears that this issue only occurs when iNotify is running while the delete actions are performed. Afterward, Syncthing's regular rescan doesn't even detect that the folder is out-of-sync. If Syncthing is restarted/refreshed from GUI on the machine running iNotify, the deletes finally sync.

**Comment by Zillode** [comment]
This is probably related to #108. Could you try the following build: http://wilma.vub.ac.be/~lhoste/public/syncthing-inotify.zip

**Comment by meztup** [comment]
Thanks, but the problem persists. I'm now on SyncThing 0.13.4.

Interesting notes to add (that might be helpful):

1) The syncthing-inotify command window reflects the deletes immediately, but syncthing on the same machine fails to realize that the file count has decreased. and never syncs the delete--even after the rescan interval passes.
2) Syncthing stops syncing the folder without "help". With inotify running, additions are synced (but not deletes). Quitting inotify results in syncthing not syncing the folder at all (but it thinks everything is fine.)
3) Manual rescans still function as expected, but the automatic rescans continue to be broken until syncthing itself is restarted.

**Comment by AudriusButkevicius** [comment]
Are the files ignored?

**Comment by meztup** [comment]
Nope. My ignore lists are empty. Here's an excerpt from the log--I removed some INFO lines b/c they looked like they might contain sensitive IDs and such.

[syncthinglog(edited).txt](https://github.com/syncthing/syncthing-inotify/files/285717/syncthinglog.edited.txt)

22:17 -- performed regular file create and delete actions
22:19 -- started inotify
22:20 -- performed 2 more create and delete actions
22:25 -- forced a rescan via syncthing web interface

My rescan interval is set at 60 and I created a new folder pair instead of using my old 0.12 folders

**Comment by AudriusButkevicius** [comment]
Which file did you actually delete?

**Comment by meztup** [comment]
Deleted without inotify running:
-->New Microsoft Office Publisher Document.pub

Deleted with inotify running:
-->New Contact.contact
-->New Journal Document.jnt

I deleted these files on the machine doing the logging. I am NOT using inotify on the "other" machine.

Please let me know if you need logs for a specific scenario.

**Comment by AudriusButkevicius** [comment]
Sorry but your report is very poor.

Can you actually produce an isolated detailed step by step case on how to reproduce this?

**Comment by AudriusButkevicius** [comment]
Also next time you produce a log at STTRACE=model,scanner

**Comment by AudriusButkevicius** [comment]
Ok I've reproduced the issue.

**Comment by meztup** [comment]
Set up two machines (Machine A and Machine B) with Windows 7 x64, syncthing 0.13.4, and a synced folder between them.
Have inotify 0.8 available on Machine A.

Actions | Expected Result | Actual Result
----------|----------------------|------------------
1. Start syncthing on both machines | Machines connect and perform initial scans on synced folder | As Expected
2. Add a file to the synced folder on Machine A | Syncthing syncs the file to Machine B after the scan interval expires. | As Expected
3. Delete the file from the synced folder on Machine A | Syncthing syncs the delete to Machine B after the scan interval expires | As Expected
4. Start inotify on Machine A | Inotify command window opens, indicating some info about the folders being watched | As Expected
5. Add a file to the synced folder on Machine A | Syncthing syncs the file immediately, thanks to inotify. | As Expected
6. Delete the file from the synced folder on Machine A | Syncthing syncs the delete immediately, thanks to inotify. | :boom: Nothing happens here. The file persists on Machine B and syncthing never syncs the delete.
7. Add another file to the synced folder on Machine A | Syncthing syncs the file immediately, thanks to inotify. | As Expected
8. Shutdown inotify on Machine A. Make any changes you like to the synced folder on Machine A | Syncthing syncs file additions, modifications, and deletes based on its regular recurring scan |  :boom: Syncthing stops syncing the folder (unless it is restarted on Machine A.)
9. Manually initiate a syncthing scan on Machine A | Syncthing syncs file additions, modifications, and deletes | As Expected
10. Make any changes you like to the synced folder on Machine A | Syncthing syncs changes |  :boom: Syncthing completely misses all changes and doesn't sync them until it is restarted.

**Comment by AudriusButkevicius** [comment]
So I think "until restarted" is not true, rather "until rescanned manually?"

**Comment by AudriusButkevicius** [comment]
Can close this, fix is in:

https://github.com/syncthing/syncthing/pull/3206

**Comment by Zillode** [comment]
:+1: thanks for your report
