### ISSUE TITLE
Make handling of ignores in syncthing-notify compatible with syncthing 0.13

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing-inotify#110]
My patch that prevents notify from aborting on ignored folders does not work anymore. I traced the issue to the getIgnorePatterns function. It returns without an error but the return value is an empty array. Already the ignores["patterns"] array is empty. As I do not know json or the syncthing http API I stopped tracing the problem there and would very much appreciate it if somebody might take it up from there. Maybe something relevant changed in syncthing API that was not prominently announced in the changelog?

**Comment by AudriusButkevicius** [comment]
I think there are no more regex support in 0.13, so @Zillode needs to use the same glob package we do.

**Comment by imsodin** [comment]
Does this mean https://docs.syncthing.net/rest/db-ignores-get.html is outdated and the field name for the new kind of patterns has changed? Just asking because not the handling of the globs (whatever the implementation) is failing but there is nothing in the field called "patterns".

**Comment by AudriusButkevicius** [comment]
It still should return stuff, but the stuff we return is no longer valid regular expressions like it used to be.

@calmh this actually was a breaking change which we forgot to mention.

**Comment by imsodin** [comment]
Ok I looked a bit more at what syncthing-inotify gets from the /rest/db/ignores call: There is the ignore field as described in the documentation, but no patterns field. Instead there is a expanded field, which contains all strings in the .stignore file and the includes. However any kind of prefix like ! or (?d) is stripped away. From what I understand syncthing-inotify does nothing but query /rest/db/ignores, check for errors and json.Unmarshal the result. The documentation on /rest/db/ignores needs an update, but I obviously did not understand it such that I could do it myself.

**Comment by AudriusButkevicius** [comment]
So it's essentially not ready to handle 0.13 ignores, that's all it seems.

**Comment by imsodin** [comment]
@Zillode 
So it looks like it is not (neatly) possible to support both 0.12 and 0.13 in one version. I think it would be a good idea to use syncthing's ignore package in syncthing-inotify instead of implementing the globing again. Thus consistent behavior is guaranteed and it should be fairly simple (hopefull) to implement. If you want, I could give it a try. However if you want it quickly and neatly done and have the time yourself, I do not want to interfere.

**Comment by Zillode** [comment]
Good idea. I think we can even drop support for 0.12 if needed. As long as we are not v1.0 we should not try too hard to be backwards compatible.
Please go ahead with your effort. I'll focus on https://github.com/syncthing/syncthing-inotify/issues/108 when I have the time

**Comment by imsodin** [comment]
@AudriusButkevicius @calmh 
I currently see two possibilities to create a Matcher struct in syncthing-inotify: Parse the .stignore file again in syncthing-inotify or parse the expanded field from /rest/db/ignores call to syncthing. The first option is directly possible with the current methods in ignore.go, but redundant as the same file is parsed twice. So the second option would be (probably?) more efficient, but I need the function addPattern that is currently defined within parseIgnoreFile. That I do not have to copy paste this code, I would need to modify ignore.go, such that addPattern becomes an independent exported function AddPattern. Is there a reason why it is implemented as presently or can I go ahead with modifying ignore.go and post a PR?

**Comment by AudriusButkevicius** [comment]
I think you can just the expanded list.

Just join the list with \n, and feed it to the ignires.New (might need to wrap it in a buffer)

**Comment by imsodin** [comment]
I do not quite understand: ignores.New just takes one argument (a bool) whether there should be a cache or not and returns a pointer to an newly initialized "empty" Matcher struct. So how do I feed it the expanded list?

**Comment by AudriusButkevicius** [comment]
Sorry, Load or whatever method that actually loads the file content, just like the tests do it. I am on the phone, so looking up the code is hard.

**Comment by imsodin** [comment]
In the tests either a file in a testdata folder is used or a tempfile is created. However that would be useless in this case, as instead of creating a tempfile from /rest/db/ignores stuff, I could just as well use the original .stignore file, or am I missing something? I am starting to think that reparsing the .stignore file is more straight forward than calling the http api and using the expanded field, as these strings have to be parsed as well. And it does need minimal code adjustments (none on the part of syncthing).

**Comment by imsodin** [comment]
Unless I completely borked it up this was much easier than I thought, see PR #111.
