### ISSUE TITLE
-skip-folders option doesn't seem to work

### ISSUE THREAD

**Issue by Tstassin** [syncthing/syncthing-inotify#113]
Running 
`./syncthing-inotify -skip-folders="@eaDir" [...]`

I want to ignore 4000+ ../@eaDir/.. folders and it doesn't seem to work, the log accounts for the numerous changes in these folders :
`[OK] 13:35:01 Syncthing is indexing change in REDACTEDFOLDER: [REDAC/TED/PATH/@eaDir/REDACTEDFILE.EXT]`

Any idea ?

**Comment by imsodin** [comment]
What you want to achieve is not the purpose of -skip-folders. You need to ignore "@eaDir" in a .stignore file as described in the [syncthing documentation on ignoring](https://docs.syncthing.net/users/ignoring.html). The confusion arises from the distinction of filesystem folders (generally what one would assume) and syncthing folders, which are more or less shares.

The help line could be improved to clarify this. However additionally I looked up whether syncthing-inotify treats this input as folder IDs or folder labels. It is folder IDs. Is this necessary and if not, should it check for matches against labels and IDs or only IDs? This is obviously relevant to -folders as well.

**Comment by Tstassin** [comment]
Thanks for your input ! I understand that I was crong in my understanding.
`@eaDir` folders are already ignored in my `.stignore` file.
They are generated on every device by the system itself.
So for me it's not a problem of sync, it's a problem of space taken in memory by the amount of watches set by syncthing-inotify.

Every inotify watch on a folder [takes up to 1kb of memory ](https://groups.google.com/forum/#!msg/lsyncd/KZfQE9VUZFw/twTMjxWa41wJ).
100.000 folders accounts for 100Mb of space.

I know that inotify includes a way of excluding folders using regexes, maybe it could be a good update for your package ?

**Comment by imsodin** [comment]
That should not happen. I changed the code a while ago such that it does 
not install watches on ignored directories. Can you provide a logfile 
please with verbosity=4.

**Comment by Tstassin** [comment]
Just sent you this by email.

FYI, my .stignore extract :

```
// Synology files
(?d)@eaDir
```

**Comment by imsodin** [comment]
Weird. I cannot reproduce your problem, if I create this entry in my .stignore all changes in dirs "@eaDir" are ignored. If these  dirs exist when syncthing-inotify is launched no watches get installed so nothing is trigger in syncthing. If they are created after it is started, their creation and all changes within will get noticed but ignored. Watches are recursive, but how exactly this works and whether one could keep not installing watches on ignored dirs after startup I do not know and don't currently have time to look into it.
However in the logs you sent me nothing gets ignored so the problem is there. What versions of syncthing and syncthing-inotify do you use?

**Comment by Tstassin** [comment]
Weird as you say. Some precisions I thought of recently : 
All my ignore rules are in a external file included in `.stignore`, the only line in `.stignore` is 
`#include SyncthingIgnore.txt`

I use this method to share the same set of rules between the devices...Maybe you don't support inclusion of files in `stignore` as described in [the docs](https://docs.syncthing.net/users/ignoring.html) ?

Syncthing version is always up-to-date : v0.13.7
My syncthing-inotify version must be something like two weeks old

I'm certain that my ignore rules work as intended in syncthing.

Maybe it could be this `#include [...]` thing ?

**Comment by imsodin** [comment]
Ok, then we have probably found the problem: Ignoring for the notify watches was introduced in 0.8 but only works with syncthing 0.12.x (PR #103). In syncthing 0.13.x ignoring changed which was changed in syncthing-inotify with PR #111. This is included in the very recent releases 0.8.2. So make sure you use this version.

**Comment by Tstassin** [comment]
That was it !
I was still running 0.8, hadn't seen the new release of 3 days ago.
Thanks for your time
