### ISSUE TITLE
Add option to ignore specific directory

### ISSUE THREAD

**Issue by klausenbusk** [syncthing/syncthing-inotify#117]
Hello

I use Hexchat as IRC client and it write log like all the time.

It would be nice if I somehow could let syncthing-inotify ignore `~/.config/hexchat/logs` and then just let syncthing rescan it every x minute.

Regards
Kristian

**Comment by AudriusButkevicius** [comment]
It pulls ignores from syncthing.

**Comment by klausenbusk** [comment]
I award of that, but I don't want it to ignore the directory. I want it to use the rescan mechanism instant of inotify for that folder.

If I use inotify, it is trigged multiple times every minutes

**Comment by AudriusButkevicius** [comment]
The rescan mechanism is more or less disabled when running inotify, unless you manually press the button.

**Comment by imsodin** [comment]
The only workaround I see to achieve what you want is to ignore this directory via ".stignore" in the current syncthing folder X and create a new syncthing folder Y just for this directory and ignore this folder in syncthing-inotify via "-skip-folders=Y". However that is not really practicable for many such directories.
