### ISSUE TITLE
Can't save settings while syncthing-inotify is running

### ISSUE THREAD

**Issue by djgaspa** [syncthing/syncthing-inotify#118]
Changes to the settings that are saved while syncthing-inotify is running are lost at restart of syncthing. Seems like syncthing-inotify prevents modifications to config.xml file. If I close syncthing-inotify, and then save settings, che config.xml is updated correctly.

This happens with the following software:
- syncthing-windows-amd64-v0.13.10.zip
- syncthing-inotify-windows-amd64-v0.8.2.tar.gz

**Comment by Zillode** [comment]
Thanks!

**Comment by kozec** [comment]
Hello.

Would it be possible to make release with this fix? I'm testing ST-GTK with current daemon release candidate and this issue prevents any configuration changes on Windows.
