### ISSUE TITLE
What's the difference between the provided syncthing-inotify.service and the one from the Arch Wiki?

### ISSUE THREAD

**Issue by mindstormer12** [syncthing/syncthing-inotify#120]
What's the difference between the provided syncthing-inotify.service and the one from the [Arch Wiki](https://wiki.archlinux.org/index.php/Syncthing#Custom_Settings)?  As an Arch user, should I use the one in this github instead of the one from the wiki?

**Comment by imsodin** [comment]
The part of the Arch Wiki you linked to shows a drop in service file to change the command line options when starting syncthing-inotify. The text above the sample given is not overly clear that this is just an example of something you could place there (there is an "e.g." at the end). So unless you need to change the behavior of syncthing-inotify you should be fine without adding anything manually to the standard syncthing-inotify service file.
