### ISSUE TITLE
Using rjeczalik/notify

### ISSUE THREAD

**Issue by aviau** [syncthing/syncthing-inotify#124]
Hello!

I have noticed that this project uses [Zillode/notify](https://github.com/Zillode/notify), which seems to be a fork of [rjeczalik/notify](https://github.com/rjeczalik/notify). Issues are disabled on Zillode/notify so I am not able to comment there.

Has there been any efforts to contribute Zillode/notify changes to rjeczalik/notify? Or is syncthing-inotify always going to be using Zillode/notify?

Thanks,

**Comment by imsodin** [comment]
There are three commits that differ between the two. The latest one was due to my PR #103 / PR Zillode/notify#3. There is the open issue rjeczalik/notify#79 that is relevant, but I got no reaction to my message there. It seems that repo is abandoned.

**Comment by aviau** [comment]
> I got no reaction to my message there.

Maybe it should be worth sending over the pull request?

If that dosen't work, should issue be enabled on Zillode/notify? It will probably become a dependency for mainline Syncthing, this means that it has to be included in Debian, and I am bit reluctant to package libraries that disable issues as this is an useful communications channel between upstream and downstream.

//cc @Zillode

**Comment by Zillode** [comment]
My fork was required to support some missing features. Unfortunately, these changes have not been merged upstream (yet?). I'll enable the issue tracker for https://github.com/Zillode/notify. Thanks,

**Comment by calmh** [comment]
As they say, open source is free as in a puppy - you've adopted one and now it's yours to care for :)
