### ISSUE TITLE
Why not push latest releases to apt.syncthing.net?

### ISSUE THREAD

**Issue by wonderbeyond** [syncthing/syncthing-inotify#125]
`v0.8.3` has a significant fix for me, but cant seen in apt repository.

The latest version I can get from apt repo is `v0.8.2`
```
# apt-get update
# apt-cache show syncthing-inotify | grep Version
Version: 0.6.7-42-gc612496
Version: 0.8.2
Version: 0.7
```

I want it, Thanks!

**Comment by calmh** [comment]
This is on my, and I had forgotten. It's published now. :)

@Zillode if you remember, feel free to prod me when you tag a new release.

**Comment by wonderbeyond** [comment]
I'm very glad, But can this process get automatic?

**Comment by calmh** [comment]
Theoretically it could, but since there is package signing and stuff involved there are certain security aspects that I think benefit from manual intervention.
