### ISSUE TITLE
Please replace v0.8.3 lightweight tag with annotated

### ISSUE THREAD

**Issue by dionorgua** [syncthing/syncthing-inotify#126]
Hi,

It looks like 0.8.3 release was (probably by accident) tagged using lightweight tag (while v0.8.2 is annotated).

```shell
git clone https://github.com/syncthing/syncthing-inotify.git
...
git checkout v0.8.3
git describe v0.8.2-8-gdcc94b1
v0.8.2-8-gdcc94b1
```
This breaks automated tools like `dh-make-golang`. 

Could you please update it if possible?

See similar issue for details: https://github.com/russross/blackfriday/issues/196

**Comment by Zillode** [comment]
Done, thanks
