### ISSUE TITLE
Crash on changes in files with long path/filename on Windows

### ISSUE THREAD

**Issue by NothingWeAre** [syncthing/syncthing-inotify#128]
When trying to delete file with path/filename:
`C:\Web_Development\Projects\trol_symfony\src\var\cache\dev\annotations\ff\5b5b435d5472616e73706f727469725c4170706c69636174696f6e5c54524f4c5c42756e646c65735c54524f4c46696e616e63655c456e746974795c5072696e7461626c6542696c6c247061796d656e74496e446966666572656e7443757272656e637952617465405b416e6e6f745d5d5b315d.doctrinecache.data`

syncthing-inotify crashes with errors attached in file
[crash.txt](https://github.com/syncthing/syncthing-inotify/files/425597/crash.txt)

**Comment by calmh** [comment]
[That line](https://github.com/Zillode/notify/blob/master/watcher_readdcw.go#L380) assumes the returned buffer is no longer than MAX_PATH (260 characters) which apparently doesn't hold for that path (320 characters). Seems like a misunderstanding of the API in the notify package.

**Comment by Zillode** [comment]
Thanks, merged upstream
