### ISSUE TITLE
macOS 10.12 erratically picking up changes

### ISSUE THREAD

**Issue by majorsl** [syncthing/syncthing-inotify#129]
I've noted since updating to 10.12 (Sierra) that syncthing-inotify seems to not be picking up changes as well as it used to on the two machines I've updated.  The one machine I haven't seems to work like a champ.  I wonder if we need a newer version using Go 1.6.3 that solved an issue with SyncThing?

https://github.com/syncthing/syncthing/issues/3396

Specifically Computers:

A - 10.12
B - 10.12
C - 10.11.6

Changes made on A & B are erratically updated on the others, I suspect the normal SyncThing scan interval is accomplishing the task.

A change on C propagates immediately, as expected, to the other two.

**Comment by majorsl** [comment]
Definitely getting a string of errors and the process seems locked. Log attached.
[net.syncthing.syncthinginotify.stderr.zip](https://github.com/syncthing/syncthing-inotify/files/491463/net.syncthing.syncthinginotify.stderr.zip)

**Comment by Clete2** [comment]
Are you getting these Apple Mobile File Integrity messages?

This is filling up my console log and causing an insane amount of messages.

`AMFI: allowing exception handler for 'syncthing-inotif' (400) because SIP is disabled.`

**Comment by Zillode** [comment]
@majorsl According to https://github.com/golang/go/issues/9549, you get a segfault in from the C code. Could you run with `GOTRACEBACK=crash syncthing-inotify` and capture a dump?

**Comment by majorsl** [comment]
@Zillode sure, it may take a bit to actually get an error. Interestingly, after restarting it with the above, it seems to be working. I had restarted it a couple of times before and it never saw a change. Strange. The only thing I did differently was remove the logs files before starting, I'm going to feel pretty silly if that is all it was.

@Clete2 not seeing those, I'm seeing a ton of other repeating messages on my Macs, but that's par for the course with a new major release. They'll probably start to calm down after Apple fixes a bunch of bugs or devs fix some that the new release exposed.

**Comment by majorsl** [comment]
I think I'm all set. Log file purge seems to have done the trick, I'm now sure why unless maybe something about the update to Sierra changed something about the permissions on those files.

**Comment by majorsl** [comment]
Okay, it is still crashing randomly.  I started it as was suggested with OTRACEBACK=crash syncthing-inotify - and I cannot for the life of me find where it stores the log/dump for the crash. Help?

**Comment by AudriusButkevicius** [comment]
It logs to stdout

**Comment by majorsl** [comment]
Thanks! I didn't specific a log file, I was just running it in a console widow with the command noted above. Attached is a dump from that window incase that has the relevant info. I just launched it again specifying a log file: OTRACEBACK=crash ./syncthing-inotify -logfile="/tmp/crash.txt" hopefully that will be correct.

**Comment by majorsl** [comment]
Well, I guess not. Using OTRACEBACK=crash ./syncthing-inotify -logfile="/tmp/crash.txt" just shows the normal log and then the crash similar to what I posted above. hopefully that is what you're looking for.

The crash is completely random.  It will detect changes fine for awhile and then the process will just die, seemingly when no changes are being made and it is just idle.  Sometimes it'll die moments after I launch it.

Syncthing itself is working perfectly, reporting all nodes up to date. Spot checking some of them seems to confirm they are in sync.

**Comment by majorsl** [comment]
I speculated in my original post the issue was the version of Go used to build syncthing-inotify. Looking at the 0.8.3 release, I noticed it was built with Go 1.5.3.

Yesterday, I installed Go 1.7.1 and built syncthing-inotify. I'm happy to report, 12 hours later, all 4 of my Sierra Macs are running along perfectly once again. Prior, I could never keep it running for more than 20 minutes (it typically would crash much sooner).

**Comment by Zillode** [comment]
:+1: thanks for the experiment. I'll make a new release asap.

**Comment by akohlsmith** [comment]
I'm getting this same behaviour. I will try to build from source with a new version of Go as well. Might be a few days though.

**Comment by catkfr** [comment]
I also have syncthing-inotify which will use all available CPU on two different macs since the upgrade to Sierra. Only solution I found was to kill the process...

Looking at the logs, syncthing-inotify was compiled using go 1.6.3 on both machines.

I also tried to reinstall via homebrew but could not:
`==> Downloading https://github.com/syncthing/syncthing-inotify/archive/v0.8.3.ta
Already downloaded: /Users/mserrano/Library/Caches/Homebrew/syncthing-inotify-0.8.3.tar.gz
Error: SHA256 mismatch
Expected: 3bbcce6788b44019472205c000bed2b3255a2ee08c0d20a93a9e7b22c73f3d45
Actual: 2c8ac5152056ec2f106f00f62458db478c3e8cefa11c9f6aadfeb86eccdcb811
`

**Comment by lukehamburg** [comment]
Can anyone point to a decent guide on setting up `syncthing-inotify` on macOS (Sierra)? I thought I just had to download the binary, replace `syncthing` with `syncthing-inotify` in my launchd plist and reload — but that doesn't work.  Do both daemons need to be running at the same time (`syncthing` + `syncthing-inotify`)?

**Comment by Clete2** [comment]
@lukehamburg use [Homebrew](http://brew.sh/index.html).

`brew install syncthing syncthing-inotify`

At the end of the installation, Homebrew will give you a command to run that will allow you to start each as a daemon.

To answer your last question, yes, you should run both at the same time. Syncthing will run just like normal (you can disable file scanning if you like by setting it to only scan once a day or less), and syncthing-inotify will communicate with the Syncthing API to notify it of individual file changes.

**Comment by catkfr** [comment]
Thanks for the update @Clete2

**Comment by Zillode** [comment]
@majorsl could you try https://github.com/syncthing/syncthing-inotify/releases/tag/v0.8.4-beta ?

**Comment by majorsl** [comment]
@Zillode seems to be doing the trick! Had it running for about 3 hours so far with no issues on one machine.  I'll update another one and see if I have similar results.

**Comment by majorsl** [comment]
Seems to be working well on the 4 systems I have it on.

**Comment by Zillode** [comment]
Thanks
