### ISSUE TITLE
Clarification on vendoring

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing-inotify#135]
Up until now I wasn't aware of vendoring and just manually provided the necessary dependencies in the intended version within my GOPATH. Now I wanted to update Godeps.json to include a recent bugfix in syncthing/lib/ignore. Therefore I tried to use the Godep tool to provide exactly these versions in a vendor/ subdir, but I did not get it to work (failed to find gobwas/glob in the vendor directory of syncthing). I also did not see that this was handled in cross-compile.rb or build-deb.sh.

How is the vendoring done when packaging a release?

**Comment by Zillode** [comment]
Manually:)
