### ISSUE TITLE
some clarification

### ISSUE THREAD

**Issue by ruifortes** [syncthing/syncthing-inotify#139]
I'm trying to use syncthing with two windows machines.
The directory I'm syncing is quite large with lots of small files.
I'm syncing folders that I shouldn't (like node_modules) but wanted to test performance.
It's not good. Syncthing alone seams takes forever to scanning (or maybe it hangs...)
I don't understand what he's doiing.
In the folder original machine averything is "up to date" but the remote devide tha's "syncing (30%)"
In the other the shared folder says "scanning (4%)" with 3 hour "scan time remaining"
It's not syncing any file.

I know this is not the syncthing but the next is and wanted to post this topis as one.

So the question about inotify is.
How does it work, how to run it and hoe does it interact with syncthing?

Do you need to have syncthing already started or you should just run inotify?

Is it feasible to use it with very large amount of files?

After pc sleeps (not shuts down) does it need to index everything again?

Thanks

**Comment by ruifortes** [comment]
Forget it. It really was the node_modules, they're too big.
Works great after sleep too, no need for the lengthy initialization.
Thought inotify would be necessary for the subsequent faster scanings.
Still don't understand how syncthing doesn't it but after initialization its pretty quick.
How does it figure out so quick what changed?
How does syncthing works? Anyone has any link? Couldn't find in the documentation.
Thnaks

**Comment by AudriusButkevicius** [comment]
There is a link to docs site in the web ui, also the getting started guide that gets shipped with the software.
