### ISSUE TITLE
Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by cyounkins** [syncthing/syncthing-inotify#142]
```
[WARNING] 11:22:46 Failed to perform request Post http://127.0.0.1:8384/rest/db/scan?folder=foo-bar&next=3600&sub=: net/http: timeout awaiting response headers (Client.Timeout exceeded while awaiting headers)
[WARNING] 11:22:46 Syncthing failed to index changes for  foo-bar Post http://127.0.0.1:8384/rest/db/scan?folder=foo-bar&next=3600&sub=: net/http: timeout awaiting response headers (Client.Timeout exceeded while awaiting headers)
```

Nothing notable in syncthing log, not sure if I can turn on verbose logging.

```
➜  ~ brew info syncthing-inotify
syncthing-inotify: stable 0.8.3 (bottled), HEAD
File watcher intended for use with Syncthing
https://github.com/syncthing/syncthing-inotify
/usr/local/Cellar/syncthing-inotify/0.8.3 (3 files, 6.8M) *
  Poured from bottle on 2016-10-11 at 22:53:50
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/syncthing-inotify.rb
==> Dependencies
Build: go ✘, godep ✘
```

**Comment by Zillode** [comment]
Is this reproducible? Are all calls timed out?

**Comment by cyounkins** [comment]
Well it seems to happen quite frequently. Looking at logs it seems to happen every 3 mins, 6 seconds.

**Comment by AudriusButkevicius** [comment]
Calls to scan block until they succeed.

**Comment by Zillode** [comment]
We rely on the blocking behavior so that's ok. I've checked the source and we retry the POST after some time so this warning is OK.

**Comment by Zillode** [comment]
@cyounkins are you using a slow device or do you add/modify large files in that folder?

**Comment by imsodin** [comment]
I have the same warnings often with the outlook data files that I sync with a windows machine and sometimes when big database files are modified and synced. The machines are fast, but the timeout can still be hit with big files. No problem though, the request will eventually succeed, so I think a warning is ok.
