### ISSUE TITLE
.\syncwatcher.go:402: undefined: notify.WatchWithFilter

### ISSUE THREAD

**Issue by swordyang** [syncthing/syncthing-inotify#143]
0.8.4 can not build but 0.8.3 is ok

```
go get
#github.com/syncthing/syncthing-inotify-0.8.4
.\syncwatcher.go:402: undefined: notify.WatchWithFilter
```

I grep "WatchWithFilter" in /github.com/zillode/notify and found nothing

**Comment by imsodin** [comment]
You need to update zillode/notify then, i.e. pull it.
