### ISSUE TITLE
Idea: user-based enable/disable of inotify per folder

### ISSUE THREAD

**Issue by psiegl** [syncthing/syncthing-inotify#146]
This is more a user request then an actual issue or bug.

I currently have some folders synchronized by syncthing, which more or less behave like archives. Polling is sufficient for these folders, since files don't change that often. On the other hand I do have folders synchronized by syncthing, where inotify is essential, since I use them frequently to exchange data between a ton of nodes. The current inotify just offers to be enabled for all folders or for none (run it or don't). To this, there is a need to change the flag "fs.inotify.max_user_watches" when a magnitude of files / folders will be synchronized by syncthing, which can by the way just be changed by root, which is therefore limited to users who do have root access.

I think it would be handy to have a flag / bit that allows to enable or disable inotify per folder. I even think it would be sufficient to enable or disable inotify just as of the root folder that is handled by syncthing, not for each folder or file that is within the root folder and handled by syncthing. I would guess that this would be just a simple flag within the config.xml file that could be even exposed to the GUI.

What do you think? Any plans in having such capability?

**Comment by AudriusButkevicius** [comment]
Have you tried `-help` on the program?
https://github.com/syncthing/syncthing-inotify/blob/master/syncwatcher.go#L190

**Comment by psiegl** [comment]
Interesting. Haven't seen this option. Although it is not comfortable, it is handy. :-)
