### ISSUE TITLE
syncthing-inotify service fails with exit code 1 when there are no folders

### ISSUE THREAD

**Issue by mindstormer12** [syncthing/syncthing-inotify#148]
syncthing-inotify service fails with exit code 1 when there are no folders for the raspian package. I had to do some troubleshooting to realize this. Shouldn't it return exit code 0 even when there are no folders, so that subsequently, adding folders will automatically be inotifyed as opposed to needing to restart the service after the folders are added, since it failed?

In my scenario, I typically configure all my settings and enable both syncthing and syncthing-inotify serivces before I actually add any folders for devices to sync so that they will be synced using proper settings.

P.S. I was told submit the issue here, not the official syncthing github, but all I did was install the official [Syncthing repository](https://apt.syncthing.net/) and the Syncthing package--syncthing-inotify service was made available this way. Is syncthing-inotify built-in to Syncthing or are these two completely independent projects? Are there plans for syncthing to incorporate syncthing-inotify eventually or are they planning on implementing their own solution?

**Comment by imsodin** [comment]
Just returning 0 wouldn't really help, as adding a folder still wouldn't restart syncthing-inotify.

@Zillode Is there a reason for [aborting when there is no folder](https://github.com/syncthing/syncthing-inotify/blob/master/syncwatcher.go#L313)? Couldn't that just be allowed, such that if a config change comes in via `watchSTEvents()` it gets restarted (at least if run by the systemd script).

Regarding the PS: It is in a separate repository of the same organisation, so something of a "side project". There is ongoing work to include it with syncthing: syncthing/syncthing#2807
