### ISSUE TITLE
[v0.3] Unable to access files on Windows

### ISSUE THREAD

**Issue by Schroedingers-Cat** [syncthing/syncthing-inotify#15]
Win7 x64, Syncthing-Inotify v0.3, Syncthing 0.10.x

Syncthing-Inotify sometimes won't "release" files so my programs cannot access them. My only option is to kill the process syncthing-inotify. I don't have a recipe to reproduce the behaviour yet, but it definitely affects files that are ignored by syncthing itself.

**Comment by Zillode** [comment]
Thanks for raising an issue, I'm trying to reproduce this as well but I did not manage this yet.
I also need to make a new release that integrates the ignored Syncthing patterns, that will probably solve it for you.

**Comment by Schroedingers-Cat** [comment]
Using a project folder of Unity3D, I can reproduce the behaviour. When I startup Unity, a folder called "Temp" is created by Unity3D. When closing Unity3D that folder should also get deleted. With syncthing-inotify it won't. The folder stays there and you cannot even open it with the Explorer. You have to kill syncthing-inotify. I hope this helps to find the root cause?

**Comment by Zillode** [comment]
I'll run unity3d and see what happens, thanks

**Comment by Zillode** [comment]
I tried launching and exiting unity3d and found no such problems. I can just remove the whole project folder as well.
@gharlok : simply creating and deleting a folder is enough for you to trigger this issue?

**Comment by gharlok** [comment]
after some more testing: 
- if the folder is not empty it can't be deleted - normally Win would delete the folder with all subfolders and files
- if the folder is empty deleting is no problem

**Comment by Zillode** [comment]
I confirm the bug, but need to wait upstream to fix https://github.com/howeyc/fsnotify/issues/56 and https://github.com/go-fsnotify/fsnotify/issues/42

**Comment by Zillode** [comment]
I might have found something, could you try with v0.4 (https://github.com/syncthing/syncthing-inotify/releases/tag/v0.4)?

**Comment by gharlok** [comment]
I just tried v0.4 - but same behaviour as before for me ...
tried just a second time and now it's working ?
OK - I cannotdelete a (not empty) folder created before syncthing-inotify was started - I can delete folders created while syncthing-inotify is running - and only while this instance is running - I cannot delete folders after a restart of syncthing-inotify

**Comment by Schroedingers-Cat** [comment]
It looks like Unity is now able to create and delete it's Temp folder without problems with the new v0.4. However, the v0.4 causes 100% load on one cpu core even after an hour of idle.

**Comment by gharlok** [comment]
@Schroedingers-Cat : I have no special CPU-Load
Recreating the Issue: I tried several times today and in some cases i could delete the folder and in some I couldn't - but at the moment I have no clue when yes and when no ... mayba some Windows Magic :-(

**Comment by Zillode** [comment]
Fixed in https://github.com/syncthing/syncthing-inotify/commit/aad5cad3f47b682fd02a3130389a9bced1aa6467, https://github.com/syncthing/syncthing-inotify/commit/71143d2d6f725b956d87cb1839a16a3baa7cabbb and https://github.com/syncthing/syncthing-inotify/commit/e73102fefdc73230736006a96ca5c1ff6c71eb0f
