### ISSUE TITLE
Tests fail if run collectively and pass individually

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing-inotify#150]
For me tests TestSTEvents (fewest), TestFilesAggregation and TestDeletesAggregation (both almost always) fail inconsistently when I run all tests at once (`go test -v`), but they always pass when I run them individually (`go test -v -run TestFilesAggregation`). This is the same for v0.8.4.
Can anyone reproduce this?

**Comment by grb43** [comment]
Yep. I just tried the one run  (go test -v) and both TestSTEvents and TestFilesAggregation failed; TestDeletesAggregation passed. Both the failed tests passed when run individually.

Note, I am using a slightly modified version (per PR #147) which is using Go vendering rather than Godeps. Otherwise the code is untouched.

**Comment by grb43** [comment]
Oops, meant to attach the log of the failed tests.
[failed_tests.txt](https://github.com/syncthing/syncthing-inotify/files/737261/failed_tests.txt)

**Comment by Zillode** [comment]
Could you try again on master? (https://github.com/syncthing/syncthing-inotify/commit/6206b6c8b4313366d659c24415774b1651d6f167)

**Comment by imsodin** [comment]
Almost the same, 4/10 tries failed, but the failing functions were `TestSTEvents` (same) and `TestAggregateChanges` (instead of `TestFilesAggreagation` and `TestDeletesAggregation`).

**Comment by decathorpe** [comment]
I'm still hitting these random test failures with the latest release (0.8.7), which is the same as master right now.

**Comment by imsodin** [comment]
@decathorpe I just committed changes that fixed it for me to master (i.e. not in any release yet).

**Comment by decathorpe** [comment]
@imsodin I just did a test build, and the tests have passed on all of fedora's architectures. Do you think a new release will be tagged soon, or should I do a snapshot build of git master (I guess it is stable enough)?

**Comment by imsodin** [comment]
It is also you, who depends on compatibility with syncthing regardless of vendoring, right? Because then thu upcoming 0.14.37 release will break your build again and releasing twice just for that would be too much - so I would like to wait for that release.

**Comment by decathorpe** [comment]
Yeah, that's me ... I'll wait for the next release (that contains all fixes) then. Thank you! :+1:
