### ISSUE TITLE
syncthing-inotify watches all ZFS datasets

### ISSUE THREAD

**Issue by as-com** [syncthing/syncthing-inotify#152]
I use ZFS on my server, and when I tried to remove a Docker container...
```
Error response from daemon: Driver zfs failed to remove root filesystem bfd[...]c5b: exit status 1: "/usr/sbin/zfs zfs destroy -r zroot/2cbc[...]475c" => cannot destroy 'zroot/2cb[...]75c': dataset is busy
```

Hmmm...
```
[andrew@hubble ascom-ng]$ grep zroot/2cb[...]75c /proc/*/mounts
[...]
/proc/4675/mounts:zroot/2cb[...]75c /var/lib/docker/zfs/graph/2cb[...]75c zfs rw,relatime,xattr,noacl 0 0
[andrew@hubble ascom-ng]$ ps -ef | grep 4675
andrew    4675     1  0 Jan23 ?        00:01:31 /usr/bin/syncthing-inotify -logflags=0
andrew   22670 10231  0 23:29 pts/16   00:00:00 grep 4675
```

So it seems syncthing-inotify was watching something in the Docker container! Why was syncthing-inotify holding on to the ZFS dataset, which isn't attached to Syncthing?

**Comment by imsodin** [comment]
That should not happen, even if there is convoluted symlinks involved, as neither syncthing-inotify nor the backend does follow symlinks (AFAIK).
I don't know anything about ZFS. Can you describe the folder structure involved?

**Comment by as-com** [comment]
@imsodin I have my Syncthing folder in /home/andrew/Sync. The server is running Arch Linux, using ZFS for everything except for the /boot/ partition. I also have a number of Docker containers, which use Docker's ZFS driver, which creates datasets in /var/lib/docker/zfs/.

I'm also confused as to why syncthing-inotify was holding my Docker containers hostage!

**Comment by Zillode** [comment]
@as-com, are you using symlinks in your Sync folder? Could you also post the content of `.stignore`?

**Comment by as-com** [comment]
@zillode there are no symlinks nor a .stignore in my Sync folder.

**Comment by Zillode** [comment]
@imsodin is it because he could be using `recursiveWatcher`? See https://github.com/Zillode/notify/blob/c2582a9d7e06fd326cdacc3a39f22634b6398cf9/tree_recursive.go#L157?

**Comment by imsodin** [comment]
I can't imagine how the ignore modifications I made to notify could be related as it is a no-op for natively recursive trees (the argument isn't used at all). I honestly have no idea in general what this might be about (naturally I suspect ZFS sorcery as I don't know ZFS...).

**Comment by K1773R** [comment]
Same for me, all datasets of a pool are watched by inotify, not just the relevant one. Luckily it ignores other pools.

**Comment by imsodin** [comment]
Couldn't this be due to the "deduplication" that ZFS does?
What I mean is (keep in mind, this is just Wikipedia knowledge): A tiny bit of data (maybe (part of) a system generated file) is present in the dataset that should be watched by inotify, but also in all the other datasets. So when inotify sets a watch all files containing that bit of data are locked.

**Comment by as-com** [comment]
@imsodin I don't use ZFS deduplication.

**Comment by Ferroin** [comment]
Even if you did, it couldn't be causing this unless something is horribly broken.  Block-level deduplication has absolutely nothing to do with inotify and doesn't interact with it in any way.

**Comment by Catfriend1** [comment]
Hi,

Does this issue still occur since Syncthing has built-in watcher now? I'm asking because I'm evaluating if ZFS is a good choice for my new Syncthing server.

**Comment by calmh** [comment]
FWIW I've been running Syncthing on FreeBSD on ZFS since forever and never seen anything like this issue. It might be Linux specific or it might be gone or it might be something else. I'd say ZFS is always a good choice for a new storage server. If Syncthing file watching for some reason doesn't work well with it, try to avoid Syncthing file watching.

**Comment by as-com** [comment]
Syncthing's built-in file watcher (not syncthing-inotify) has not caused me this issue.

**Comment by Catfriend1** [comment]
Wow, thank you very much for feedback. I think we can also close this issue then, right?
