### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by w4grfw** [syncthing/syncthing-inotify#154]
syncthing-inotify v0.8.3 from apt.syncthing.net:
panic: runtime error: index out of range
goroutine 42 [running]:
panic(0x7cd0a0, 0xc82000e060)
/usr/local/go/src/runtime/panic.go:481 +0x3e6
main.watchSTEvents(0xc8202960f0, 0xc82027e200, 0x9, 0x9)
/home/buildslave/workspace/syncthing-inotify-debian/src/github.com/syncthing/syncthing-inotify/syncwatcher.go:906 +0x5ea
created by main.main
/home/buildslave/workspace/syncthing-inotify-debian/src/github.com/syncthing/syncthing-inotify/syncwatcher.go:288 +0x5a4

syncthing-inotify 0.8.4:
panic: runtime error: index out of range

goroutine 39 [running]:
panic(0x670280, 0xc42000c160)
	/home/pi/dev/tools/go/src/runtime/panic.go:500 +0x1a1
main.watchSTEvents(0xc420257ef0, 0xc420258000, 0x9, 0x9)
	/home/pi/dev/src/github.com/syncthing/syncthing-inotify/syncwatcher.go:920 +0x15c
created by main.main
	/home/pi/dev/src/github.com/syncthing/syncthing-inotify/syncwatcher.go:283 +0x396

**Comment by satter** [comment]
I've encountered same error after syncthing upgrade to 0.14.22

**Comment by calmh** [comment]
At a guess, its reacting badly to getting an empty event array back. This is a recent change in syncthing...

**Comment by imsodin** [comment]
@calmh Good guess.
We should document API changes both in release notes and documentation (or at least create an issue in the docs repo such that there is a backlog). Not that it would have changed anything for me in this case - I was aware of the change but didn't make the link not syncthing-inotify.
