### ISSUE TITLE
Watchers are not registered with negative ignore rules 

### ISSUE THREAD

**Issue by nalt** [syncthing/syncthing-inotify#161]
Syncthing allows native ignore patterns in ``.stignore``, such as:
> !/a
> !/b
> /*
The use-case for this is to sync some folders from the home directory.

What happens: With the above configuration, syncthing-inotify does not register any watchers. The reason is that the filter from ``createIgnoreFilter()`` returns true for the root folder. The filter function does return false for folders a,b, but these folders never get passed to the filter after the root folder has been rejected. Syncthing itself correctly scan the directories a and b.

What should happen: Watchers should be registered to folder a, b and their subfolders.

**Comment by imsodin** [comment]
Thanks for uncovering this!
The PR I (mistakenly) referenced has nothing to do with this issue. I will see how to fix this.
