### ISSUE TITLE
crash on Mac OS

### ISSUE THREAD

**Issue by fondemen** [syncthing/syncthing-inotify#166]
Hi there,

syncthing-inotify crashes on Mac OS X 11.12.4 (Sierra) with the following exception:

panic: runtime error: index out of range

goroutine 30 [running]:
panic(0x43d9ea0, 0xc82000a090)
	/Users/lhoste/Libs/go/src/runtime/panic.go:464 +0x3e6
main.watchSTEvents(0xc820180390, 0xc8200a28c0, 0x4, 0x4)
	/Users/lhoste/tmp/go-workspace/src/github.com/syncthing/syncthing-inotify/syncwatcher.go:960 +0x5ea
created by main.main
	/Users/lhoste/tmp/go-workspace/src/github.com/syncthing/syncthing-inotify/syncwatcher.go:286 +0x639

This crash souds weird as there are no folder named /Users/lhoste on my machine...

**Comment by imsodin** [comment]
What version of syncthing-inotify are you using (`syncthing-inotify -version`)?

**Comment by fondemen** [comment]
This is syncthing-inotify v0.8 (go1.6 darwin-amd64)

**Comment by imsodin** [comment]
In that case this is most likely #154. You need to upgrade to v0.8.5 with Syncthing newer than 0.14.22 (not entirely sure whether that is the earliest version this change is in).

**Comment by fondemen** [comment]
Problem solved !
Thanks a lot...
I thought I had upgraded.
