### ISSUE TITLE
panic: notify: epoll_wait(2) error function not implemented

### ISSUE THREAD

**Issue by hillyu** [syncthing/syncthing-inotify#167]
This is fixed on upstream,  please refer to: [golang/sys@324e137](https://github.com/golang/sys/commit/324e137) . You might need to update the vendor/dep files.

**Comment by imsodin** [comment]
This has been fixed in the notify backend (https://github.com/rjeczalik/notify/pull/116), which is now up-to-date in the vendor dir. It is thus available through master, but not in a release (@Zillode).
