### ISSUE TITLE
0.8.6 vendor directory incomplete

### ISSUE THREAD

**Issue by ilovezfs** [syncthing/syncthing-inotify#168]
Attempting to build 0.8.6 from https://github.com/syncthing/syncthing-inotify/archive/v0.8.6.tar.gz leads to
```
==> go build -ldflags -w -X main.Version=0.8.6
vendor/github.com/syncthing/syncthing/lib/ignore/ignore.go:22:2: cannot find package "github.com/syncthing/syncthing/lib/osutil" in any of:
	/private/tmp/syncthing-inotify-20170615-44753-1facjm/syncthing-inotify-0.8.6/src/github.com/syncthing/syncthing-inotify/vendor/github.com/syncthing/syncthing/vendor/github.com/syncthing/syncthing/lib/osutil (vendor tree)
	/private/tmp/syncthing-inotify-20170615-44753-1facjm/syncthing-inotify-0.8.6/src/github.com/syncthing/syncthing-inotify/vendor/github.com/syncthing/syncthing/lib/osutil
	/usr/local/opt/go/libexec/src/github.com/syncthing/syncthing/lib/osutil (from $GOROOT)
	/private/tmp/syncthing-inotify-20170615-44753-1facjm/syncthing-inotify-0.8.6/src/github.com/syncthing/syncthing/lib/osutil (from $GOPATH)
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
```

It seems the vendor directory is incomplete. If I manually intervene and run
```
go get github.com/syncthing/syncthing/lib/osutil
```
first, then running `go build -ldflags -w -X main.Version=0.8.6` succeeds.

**Comment by imsodin** [comment]
I missed the new dependency of Syncthing's ignore library when updating it...
This is fixed by https://github.com/syncthing/syncthing-inotify/commit/f628a84902f9ffdf9cb439294f83383b60d7efae

@Zillode Should I do a "bugfix" release for this?

**Comment by ilovezfs** [comment]
Thanks @imsodin!

**Comment by Zillode** [comment]
Yes, with a new annotated tag (git tag -a)

On Jun 16, 2017 11:47, "ilovezfs" <notifications@github.com> wrote:

Thanks @imsodin <https://github.com/imsodin>!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/syncthing/syncthing-inotify/issues/168#issuecomment-308983266>,
or mute the thread

**Comment by imsodin** [comment]
> Yes, with a new annotated tag (git tag -a)

@Zillode Meaning that letting github add the tag on release isn't correct? That's what I did for v0.8.6.

**Comment by ilovezfs** [comment]
@Zillode I assume you mean a new tag named 0.8.6.1 or 0.8.7?

**Comment by Zillode** [comment]
I haven't use tagging through GitHub but I actually created an annotated
tag 0.8.6 before I clicked release. The website mentioned that the tag was
already there so I think GitHub did not create the tag.

Simply execute `git tag v0.8.7 -a`
And build

**Comment by imsodin** [comment]
The new release is out - thanks @ilovezfs for reporting!

**Comment by ilovezfs** [comment]
Thanks @imsodin!
