### ISSUE TITLE
Integrate Syncthing ignore patterns

### ISSUE THREAD

**Issue by Schroedingers-Cat** [syncthing/syncthing-inotify#17]
Observing the terminal output of v0.4, syncthing-inotify seems to react to changes in folders and files that are ignored by syncthing (defined in .stignore). The ignore patterns should also be ignored by syncthing-inotify.

**Comment by AudriusButkevicius** [comment]
It already does.
You will have to provide exact file name, pattern and output

**Comment by Schroedingers-Cat** [comment]
I defined the following pattern in the `.stignore`:
```
#include st_ignore_standard.txt
#include st_ignore.txt
```
The file `st_ignore.txt` contains the following patterns:
```
/[ignored_folder]
```

The file `st_ignore_standard.txt` holds patterns I ignore in all of my syncthing repos:
```
.DS_Store
.Spotlight-V100
.Trashes
~*
ehthumbs.db
desktop.ini
Thumbs.db
._*
.sync
.git
.Trash-1000
```

This is the terminal output:
```batch
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Windows\system32>"C:\Program Files\Tools\Syncthing\syncthing-inotifyV04.exe" -api="[...]"
[...]
2015/02/24 14:40:02 Watching [repo_name]: [path\to\syncthing_repo]
[...]
2015/02/24 14:40:12 Change detected in [path\to\syncthing_repo]\[ignored_folder]\Neuer Ordner
2015/02/24 14:40:13 Syncthing is indexing change in [repo_name]: [ignored_folder]\Neuer Ordner
2015/02/24 14:40:24 Change detected in [path\to\syncthing_repo]\Balloon Arena
2015/02/24 14:40:24 Change detected in [path\to\syncthing_repo]\[ignored_folder]\Neuer Ordner\Neues Textdokument.txt
2015/02/24 14:40:24 Change detected in [path\to\syncthing_repo]\[ignored_folder]\Neuer Ordner
2015/02/24 14:40:25 Syncthing is indexing change in [repo_name]: [ignored_folder]\Neuer Ordner\Neues Textdokument.txt
2015/02/24 14:40:34 Change detected in [path\to\syncthing_repo]\[ignored_folder]\Neuer Ordner\Neues Textdokument.txt
2015/02/24 14:40:34 Change detected in [path\to\syncthing_repo]\[ignored_folder]\Neuer Ordner\Neues Textdokument.txt
2015/02/24 14:40:34 Syncthing is indexing change in [repo_name]: [ignored_folder]\Neuer Ordner\Neues Textdokument.txt
```

As you can see from the terminal output, syncthing-inotify still reacts to changes in the folder `[ignored_folder]`. I double checked that Syncthing itself does not. It is however "woken up" by syncthing-inotify causing a "rescan" but adding/subtracting nothing to the file count.

**Comment by Zillode** [comment]
Could you post the result from http://localhost:8080/rest/ignores?folder=repo_name ?
Feel free to replace strings without the brackets (don't use [ or ] because it will break the regexp).

**Comment by Schroedingers-Cat** [comment]
```
{"ignore":["#include st_ignore_standard.txt","#include st_ignore.txt"],"patterns":["(?i)^\\.DS_Store$","(?i)^.*\\\\\\.DS_Store$","(?i)^\\.DS_Store\\\\.*$","(?i)^.*\\\\\\.DS_Store\\\\.*$","(?i)^\\.Spotlight-V100$","(?i)^.*\\\\\\.Spotlight-V100$","(?i)^\\.Spotlight-V100\\\\.*$","(?i)^.*\\\\\\.Spotlight-V100\\\\.*$","(?i)^\\.Trashes$","(?i)^.*\\\\\\.Trashes$","(?i)^\\.Trashes\\\\.*$","(?i)^.*\\\\\\.Trashes\\\\.*$","(?i)^~[^\\\\]*$","(?i)^.*\\\\~[^\\\\]*$","(?i)^~[^\\\\]*\\\\.*$","(?i)^.*\\\\~[^\\\\]*\\\\.*$","(?i)^ehthumbs\\.db$","(?i)^.*\\\\ehthumbs\\.db$","(?i)^ehthumbs\\.db\\\\.*$","(?i)^.*\\\\ehthumbs\\.db\\\\.*$","(?i)^desktop\\.ini$","(?i)^.*\\\\desktop\\.ini$","(?i)^desktop\\.ini\\\\.*$","(?i)^.*\\\\desktop\\.ini\\\\.*$","(?i)^Thumbs\\.db$","(?i)^.*\\\\Thumbs\\.db$","(?i)^Thumbs\\.db\\\\.*$","(?i)^.*\\\\Thumbs\\.db\\\\.*$","(?i)^\\._[^\\\\]*$","(?i)^.*\\\\\\._[^\\\\]*$","(?i)^\\._[^\\\\]*\\\\.*$","(?i)^.*\\\\\\._[^\\\\]*\\\\.*$","(?i)^\\.sync$","(?i)^.*\\\\\\.sync$","(?i)^\\.sync\\\\.*$","(?i)^.*\\\\\\.sync\\\\.*$","(?i)^\\.git$","(?i)^.*\\\\\\.git$","(?i)^\\.git\\\\.*$","(?i)^.*\\\\\\.git\\\\.*$","(?i)^\\.Trash-1000$","(?i)^.*\\\\\\.Trash-1000$","(?i)^\\.Trash-1000\\\\.*$","(?i)^.*\\\\\\.Trash-1000\\\\.*$","(?i)^ignored_folder$","(?i)^ignored_folder\\\\.*$"]}
```

`ignored_folder` contains a whitespace.

**Comment by Zillode** [comment]
@Schroedingers-Cat could you try http://wilma.vub.ac.be/~lhoste/private/syncthing-inotify-windows-amd64-v0.5-pre.tar.gz ?

**Comment by Zillode** [comment]
Fixed in https://github.com/syncthing/syncthing-inotify/commit/8900c4f9386ad3a3cd12794a56eb7045069922de

**Comment by Schroedingers-Cat** [comment]
Sorry, I didn't notice your answer. I just tried the v0.5pre and it seems to work. Thank you!

However, there still is the high cpu load during idle introduced with v0.4. Should I open a new issue for that?

**Comment by Zillode** [comment]
Hmm, could you try with the latest code? I recompiled it for you: http://wilma.vub.ac.be/~lhoste/private/syncthing-inotify-windows-amd64-v0.5-pre-2.tar.gz

**Comment by Schroedingers-Cat** [comment]
I tried it and the cpu load still remains. I opened #19.

**Comment by Schroedingers-Cat** [comment]
I have the impression, that v0.5pre2 still tries to access ignored paths. Example: A repo ignores the pattern `/ignored_folder`. The folder `ignored_folder` is a symlink to a non-existing/accessible directory. This is the terminal output: 
```batch
[WARNING] 2015/03/03 11:49:38 syncwatcher.go:256: open [ignored_folder]: Zugriff verweigert (permission denied)
```

This may be uninteresting, but I thought it's better to mention it.

**Comment by Zillode** [comment]
It's possible we still walk/touch the path but won't go deeper into that folder. See https://github.com/syncthing/syncthing-inotify/blob/5f98a4048549bdd3e4753867d20e5e7f5b42fe0b/syncwatcher_lib.go#L160 (and https://github.com/syncthing/syncthing-inotify/blob/5f98a4048549bdd3e4753867d20e5e7f5b42fe0b/syncwatcher.go#L267)
