### ISSUE TITLE
Versions 0.8.6 and 0.8.7 are not available through apt.syncthing.net

### ISSUE THREAD

**Issue by neckcen** [syncthing/syncthing-inotify#173]
As title says. Thanks for the hard work.

**Comment by imsodin** [comment]
@calmh Could you please update the apt repo with these releases.

**Comment by calmh** [comment]
Will do. Not at a computer currently, will report back when done. Keep the issue open.

**Comment by calmh** [comment]
0.8.7 is now in the repo
