### ISSUE TITLE
version 0.8.7 doesn't build against latest syncthing releases

### ISSUE THREAD

**Issue by decathorpe** [syncthing/syncthing-inotify#175]
It looks like the syncthing ignore API has changed recently, because I'm getting this compilation error when building against syncthing 0.14.33 or 0.14.34:

```
./syncwatcher.go:503: cannot use false (type bool) as type ignore.Option in argument to ignore.New
```

**Comment by imsodin** [comment]
It did, but we vendor the libraries from Syncthing, so there should not be a problem unless you fiddle with the ./vendor folder. And the change in the ignore library is just "cosmetic" as far as I remember, so I am not overly keen to update just for the sake of it.

**Comment by decathorpe** [comment]
Yes, I know that stuff like this is why projects vendor their dependencies. However, since I plan on submitting a syncthing-inotify package to the official fedora repositories (review request: [1]), building with bundled / vendored dependencies isn't / won't be possible due to the fedora Packaging Guidelines.

It's not a big deal right now, since syncthing itself isn't in the fedora repositories yet (though it soon will be), but not being able to build against the latest syncthing version will prevent an official syncthing-inotify package from happening.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1431868

**Comment by calmh** [comment]
I'm sure a pull request could clear this whole thing up.

**Comment by imsodin** [comment]
This being about packaging makes my "just for the sake of it" point moot ;)
