### ISSUE TITLE
Fetch configuration from syncthing/config.xml

### ISSUE THREAD

**Issue by SjonHortensius** [syncthing/syncthing-inotify#18]
It'd be pretty nice if both the address and apiKey would be fetched by this app from the actual syncthing directory. Since this app will always run on the same machine it could make configuration even easier

**Comment by Zillode** [comment]
Where should it find this information? I'm not using ~/.syncthing/config.xml but maybe I can add this as a first try...

**Comment by SjonHortensius** [comment]
If it could use the same logic as syncthing @ https://github.com/syncthing/syncthing/blob/53f1af0cabf9b97210b600a5a95572244b17217d/cmd/syncthing/main.go#L941 that'd be nice. I actually need this for automated deployment of syncthing+inotify as a glusterfs replacement and I'd be happy to create a patch

**Comment by Zillode** [comment]
Ah, good catch! Feel free to provide a patch, you just need to read the xml config.
Please update the code before you start, I did some major changes in the last few days and just pushed them to master.

**Comment by SjonHortensius** [comment]
I have implemented a reader for the current format but preferably we'd use syncthing's  *internal/config/config.go* which facilitates parsing any configuration format

**Comment by SjonHortensius** [comment]
Correct implementation can be tested by executing ./synthing-inotify --help; it'll show the values fetched from the configuration
