### ISSUE TITLE
Merge into core or explain why it's not merged into syncthing

### ISSUE THREAD

**Issue by lichtamberg** [syncthing/syncthing-inotify#184]
Could someone tell my why this is not merged into core? Would be nice to get a all in one package?

**Comment by fragtion** [comment]
Seems like it is - read the release footnotes for syncthing v0.14.40 @ https://github.com/syncthing/syncthing/releases/tag/v0.14.40

**Comment by lichtamberg** [comment]
Ah, nice, thank you!
