### ISSUE TITLE
Where's the option to enable it on Android (with inotify merged)?

### ISSUE THREAD

**Issue by rieje** [syncthing/syncthing-inotify#185]
Where's the option to enable it on Android (with inotify merged)? I don't see it anywhere.

**Comment by imsodin** [comment]
The android app already has an integrated function to detect changes - no need to enable it there. Also this function is still not fully integrated in Syncthing - it works but we are still doing smaller changes and the UI is only partially in place. If you still want to enabled it, then you find it in the advanced settings (as written in the readme).
