### ISSUE TITLE
API key exposed to other system users

### ISSUE THREAD

**Issue by capi** [syncthing/syncthing-inotify#21]
`syncthing-inotify` specifies the API key to use with `syncthing` core server via the `-api` paramter.

At least when running in Linux, this is a security issue, as the command line arguments can be read by any other local user, e.g.

    martin@linuxbox:~$ ps aux | grep notify
    root        46  0.0  0.0      0     0 ?        S    Feb16   0:00 [fsnotify_mark]
    martin   16837  0.8  0.1 792628  4304 pts/6    Sl+  23:43   0:00 ./syncthing-inotify -api=thesecretkey -target=https://localhost:7003
    martin   16865  0.0  0.0   6152   828 pts/12   S+   23:44   0:00 grep notify

Secrets should either be read from `stdin` or from a specified file, so I'd suggest to add a `-api-file` parameter that takes a filename from which the API key is read.

**Comment by Zillode** [comment]
Fixed in https://github.com/syncthing/syncthing-inotify/commit/d2c96f09344e66b627f6835d1d8d5eaae9ca5e81

**Comment by AudriusButkevicius** [comment]
You can also nuke os.Args, atleast in C that hides it from stuff like top and ps.
There is also a special syscall for that too.

**Comment by capi** [comment]
Yes, you can. But there still is a (granted: short) race condition and it is considered best practice to provide credentials via files / `stdin` for this reason. I think the fix in d2c96f0 is a valid one. Thanks for being so quick about this.
