### ISSUE TITLE
issue when files get update by local rsync

### ISSUE THREAD

**Issue by napseis** [syncthing/syncthing-inotify#24]
hi,

I'm using a rsync script to sync okular annotations into a folder monitored by syncthing with syncthing-gtk, where the monitor filesystem has been activated.

When i modify an annotation, and then copy "manually", then the chaneg is detected ok. (see below)
When i rsync from okular directory to my other dierctory, the update is not done. (see second debug below).

Thanks

MANUAL Copy:
[GB67N] 2015/03/06 15:22:57.666190 walk.go:72: DEBUG: Walk /home/intermat/aurelien/Bibliographie annotations/300236.Upadhyay-etal2013_Elastic_constitutive_laws_for_incompatible_crystalline_media__the_contributions_of_dislocations,_disclinations_and_G-disclinations.pdf.xml 131072 &{[{0xc208cc1860 true} {0xc208cc19a0 true} {0xc208cc1ae0 true} {0xc208cc1c20 true}] true 0xc208e0a5a0 998c2f2afcc3f9118a83744a689b3901 0xc208052a20 {0 0}}
[GB67N] 2015/03/06 15:22:57.666223 walk.go:307: DEBUG: checkDir /home/intermat/aurelien/Bibliographie &{Bibliographie 4096 2147484156 {63561248043 456023709 0xdb1060} 0xc208bc8000}
[GB67N] 2015/03/06 15:22:57.699921 walk.go:72: DEBUG: Walk /home/intermat/aurelien/Bibliographie annotations/.goutputstream-5AOPUX 131072 &{[{0xc208cc1860 true} {0xc208cc19a0 true} {0xc208cc1ae0 true} {0xc208cc1c20 true}] true 0xc208e0a5a0 998c2f2afcc3f9118a83744a689b3901 0xc208052a20 {0 0}}
[GB67N] 2015/03/06 15:22:57.699944 walk.go:307: DEBUG: checkDir /home/intermat/aurelien/Bibliographie &{Bibliographie 4096 2147484156 {63561248043 456023709 0xdb1060} 0xc20851a870}
[GB67N] 2015/03/06 15:22:57.699998 walk.go:103: DEBUG: error: /home/intermat/aurelien/Bibliographie/annotations/.goutputstream-5AOPUX <nil> lstat /home/intermat/aurelien/Bibliographie/annotations/.goutputstream-5AOPUX: no such file or directory
[GB67N] 2015/03/06 15:22:57.702298 walk.go:72: DEBUG: Walk /home/intermat/aurelien/Bibliographie annotations/300236.Upadhyay-etal2013_Elastic_constitutive_laws_for_incompatible_crystalline_media__the_contributions_of_dislocations,_disclinations_and_G-disclinations.pdf.xml 131072 &{[{0xc208cc1860 true} {0xc208cc19a0 true} {0xc208cc1ae0 true} {0xc208cc1c20 true}] true 0xc208e0a5a0 998c2f2afcc3f9118a83744a689b3901 0xc208052a20 {2 1}}
[GB67N] 2015/03/06 15:22:57.702314 walk.go:307: DEBUG: checkDir /home/intermat/aurelien/Bibliographie &{Bibliographie 4096 2147484156 {63561248043 456023709 0xdb1060} 0xc208bc86c0}
[GB67N] 2015/03/06 15:22:57.702420 walk.go:276: DEBUG: rescan: File{Name:"annotations/300236.Upadhyay-etal2013_Elastic_constitutive_laws_for_incompatible_crystalline_media__the_contributions_of_dislocations,_disclinations_and_G-disclinations.pdf.xml", Flags:0100666, Modified:1425651392, Version:16989, Size:47827, Blocks:[Block{0/47827/1d54923ed6335ad98e803bb064f7a85cc84c9fa95c0e1fd2fccba05574ed2e99}]} 1425651768 -rwxrwxr--
[GB67N] 2015/03/06 15:22:57.702439 walk.go:292: DEBUG: to hash: /home/intermat/aurelien/Bibliographie/annotations/300236.Upadhyay-etal2013_Elastic_constitutive_laws_for_incompatible_crystalline_media__the_contributions_of_dislocations,_disclinations_and_G-disclinations.pdf.xml File{Name:"annotations/300236.Upadhyay-etal2013_Elastic_constitutive_laws_for_incompatible_crystalline_media__the_contributions_of_dislocations,_disclinations_and_G-disclinations.pdf.xml", Flags:0100666, Modified:1425651768, Version:16996, Size:0, Blocks:[]}

RSYNC copy:

[GB67N] 2015/03/06 15:25:39.572479 walk.go:72: DEBUG: Walk /home/intermat/aurelien/Bibliographie annotations/.300236.Upadhyay-etal2013_Elastic_constitutive_laws_for_incompatible_crystalline_media__the_contributions_of_dislocations,_disclinations_and_G-disclinations.pdf.xml.TgcYAE 131072 &{[{0xc208cc1860 true} {0xc208cc19a0 true} {0xc208cc1ae0 true} {0xc208cc1c20 true}] true 0xc208e0a5a0 998c2f2afcc3f9118a83744a689b3901 0xc208052a20 {1 0}}
[GB67N] 2015/03/06 15:25:39.572512 walk.go:307: DEBUG: checkDir /home/intermat/aurelien/Bibliographie &{Bibliographie 4096 2147484156 {63561248043 456023709 0xdb1060} 0xc208bc8090}
[GB67N] 2015/03/06 15:25:39.572605 walk.go:103: DEBUG: error: /home/intermat/aurelien/Bibliographie/annotations/.300236.Upadhyay-etal2013_Elastic_constitutive_laws_for_incompatible_crystalline_media__the_contributions_of_dislocations,_disclinations_and_G-disclinations.pdf.xml.TgcYAE <nil> lstat /home/intermat/aurelien/Bibliographie/annotations/.300236.Upadhyay-etal2013_Elastic_constitutive_laws_for_incompatible_crystalline_media__the_contributions_of_dislocations,_disclinations_and_G-disclinations.pdf.xml.TgcYAE: no such file or directory
[GB67N] 2015/03/06 15:25:39.572778 walk.go:72: DEBUG: Walk /home/intermat/aurelien/Bibliographie annotations/.300236.Upadhyay-etal2013_Elastic_constitutive_laws_for_incompatible_crystalline_media__the_contributions_of_dislocations,_disclinations_and_G-disclinations.pdf.xml.TgcYAE 131072 &{[{0xc208cc1860 true} {0xc208cc19a0 true} {0xc208cc1ae0 true} {0xc208cc1c20 true}] true 0xc208e0a5a0 998c2f2afcc3f9118a83744a689b3901 0xc208052a20 {0 0}}
[GB67N] 2015/03/06 15:25:39.572811 walk.go:307: DEBUG: checkDir /home/intermat/aurelien/Bibliographie &{Bibliographie 4096 2147484156 {63561248043 456023709 0xdb1060} 0xc208c30000}
[GB67N] 2015/03/06 15:25:39.572905 walk.go:103: DEBUG: error: /home/intermat/aurelien/Bibliographie/annotations/.300236.Upadhyay-etal2013_Elastic_constitutive_laws_for_incompatible_crystalline_media__the_contributions_of_dislocations,_disclinations_and_G-disclinations.pdf.xml.TgcYAE <nil> lstat /home/intermat/aurelien/Bibliographie/annotations/.300236.Upadhyay-etal2013_Elastic_constitutive_laws_for_incompatible_crystalline_media__the_contributions_of_dislocations,_disclinations_and_G-disclinations.pdf.xml.TgcYAE: no such file or directory

**Comment by Zillode** [comment]
Hi @napseis, could you move the issue to https://github.com/syncthing/syncthing-gtk ? Syncthing-GTK uses a different inotify implementation.
Thanks

**Comment by napseis** [comment]
sure, done !
Thanks
