### ISSUE TITLE
Check for multiple instances of syncthing-inotify

### ISSUE THREAD

**Issue by hakakou** [syncthing/syncthing-inotify#25]
I'm using Windows. It would be nice if syncthing-inotify.exe would check if another instance of itself is running, and exit itself if found. 

I'm running using task scheduler, and this would make sure It does not run by mistake a second time. Else I need to check the Task Manager all the time.

**Comment by Zillode** [comment]
I suggest you write a wrapper for this, there is no cross-platform support from Go to implement this

**Comment by AudriusButkevicius** [comment]
You can always try binding to a port :dancers:
