### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rumpelsepp** [syncthing/syncthing-inotify#27]
Hi, I am creating an AUR package of syncthing-inotify for arch linux. I have to include license information into the metadata. As you do not provide any license I am not allowed to create a package. Can you help me here? :)

**Comment by Zillode** [comment]
I'll add an MPLv2 license later today. MPLv2 is used such that it can be integrated into syncthing when current limitations are resolved.

**Comment by rumpelsepp** [comment]
:+1:

**Comment by rumpelsepp** [comment]
Here it is: https://aur.archlinux.org/packages/syncthing-inotify/
I will update the commit hash when you have added the license. :)
