### ISSUE TITLE
Pause Syncthing if the file system containing watched object was unmounted.

### ISSUE THREAD

**Issue by sharethewisdom** [syncthing/syncthing-inotify#30]
It would be convenient if syncthing-inotify could pause Syncthing before anything bad happens. Something like this has been [requested before](https://github.com/syncthing/syncthing/issues/762). 

In Arch Linux, I manually mount a truecrypt volume to ~/documents whenever I need to access it. Note that this is the only watched folder, so I could manually start/stop the syncthing(-inotify) services after (un)mounting.

(I'm sorry for posting before trying this out.)

**Comment by generalmanager** [comment]
Well without inotify syncthing does stop if the .stfolder file can't be found to protect against such issues, but I am not sure what happens when inotify is involved.

**Comment by Zillode** [comment]
I don't think inotify should pause. We should forward all changes to Syncthing as they happen because we might lose events otherwise.
Also, mounting folders on a path being watched will not work because no inotify events will be created for any changes in that mounted folder.

**Comment by sharethewisdom** [comment]
ok so just for reference a possible sequence that 'd fit my usecase: 
*   mount, chown normal user recursively, check [[ -f ~/documents/sync/.stfolder ]] && start the syncthing-inotify service 
*   unmount, stop syncthing-inotify, chmod 200 ~/documents
