### ISSUE TITLE
[doc] doesn't work if webinterface uses TLS

### ISSUE THREAD

**Issue by generalmanager** [syncthing/syncthing-inotify#31]
It would be great if the documentation would mention that the webinterface has to be available via plain http for syncthing-inotify to work.

The debugging section would probably be the right place. The error was something along the lines of 404 isn't 200.

**Comment by AudriusButkevicius** [comment]
-help motherf*cker, do you read it?

**Comment by generalmanager** [comment]
Sure, that's where I looked first.
This was the output:
```
Usage of /usr/local/tools/syncthing/syncthing-inotify:
 -api="XXXsecretapikeyXXX": API key
 -csrf="": CSRF token file
 -pass="": Password
 -target="127.0.0.1:8080": Target
 -user="": Username
 -verbosity=2: Logging level [1..4]
```

But even if there were a hint to it in the --help it would still be nice to have it in the Troubleshooting section of the README.md

**Comment by AudriusButkevicius** [comment]
Interesting:
https://github.com/syncthing/syncthing-inotify/blob/master/syncwatcher.go#L133

Comma gets parsed as an optional flag.

**Comment by generalmanager** [comment]
That's funky!
