### ISSUE TITLE
INFO: Puller (folder "export", file "shared/dc/d6/dcd6507xxx"): dst stat dir: stat /export/shared/dc/d6: no such file or directory

### ISSUE THREAD

**Issue by SjonHortensius** [syncthing/syncthing-inotify#34]
We have an application that creates files in new directories, and this generates the above problem. It seems the empty directories aren't properly pushed; and then the file cannot be synced either.

I am not sure if syncthing-inotify should push empty directories, or if syncthing should create a directory when it gets pushed a file in a directory-yet-unknown.

Syncthing-inotify only logs the file, not it's parent-directory in this specific case
```syncwatcher.go:407: Syncthing is indexing change in export: shared/dc/d6/dcd6507xxx```

This is reproducable for other files as well; although syncwatcher sometimes logs creating a directory, it mostly syncs the file within instead, leading to problems

A full rescan fixes this problem btw so it seems inotify is to blame, but please let me know if this needs to be addressed in syncthing instead.

**Comment by AudriusButkevicius** [comment]
Which version of syncthing are you using?

**Comment by SjonHortensius** [comment]
this is syncthing 0.10.24; was there a recent upgrade that addressed this?

**Comment by AudriusButkevicius** [comment]
Yeah, syncthing is now a bit more clever and addresses this: https://github.com/syncthing/syncthing/issues/1399

**Comment by SjonHortensius** [comment]
Ah, thanks. I never could have guessed from the Title ;)
