### ISSUE TITLE
deletions are not detected

### ISSUE THREAD

**Issue by lilmike** [syncthing/syncthing-inotify#35]
Hi,
First off I must say my greatest thanks to you for providing this for syncthing. I have been searching for a way of syncing my folders between two servers such that the web root always has the same files for probably weeks now, and this is the fifth one I'd tried. I already use syncthing for my sharing between friends computers, but I never even thought to do it on my server -- mainly because of the scanning issue -- which is now fixed by syncthing-inotify.
With that out of the way, the issue I am writing about is that when you delete a file on one side, it's not deleted until the syncthing core scans the folder. I don't know if this is a shortcoming of inotifies themselves, or of syncthing-inotify, but just figured I'd let you know.
-Michael.

**Comment by garagatyi** [comment]
I faced the same problem. v0.5 release

**Comment by Zillode** [comment]
What platform? I think this is covered by a unit test

**Comment by garagatyi** [comment]
CentOS 7 in virtualbox on Ubuntu 12.04

**Comment by Zillode** [comment]
Can you test with --verbosity=4 and see if the file deletion event is captured?

**Comment by garagatyi** [comment]
I've tested it and found that ST-I doesn't remove folders but remove files. And if I remove folder tree, ST-I removes all files, but not folders.

**Comment by garagatyi** [comment]
Also it produces huge amount of logs with --verbosity=4 even when there is no changes in tracked folders and files (I don't know why but "changes detected" phrase is present in logs). 
Here is log: https://gist.github.com/garagatyi/d735fa2494a1c5acc101
