### ISSUE TITLE
Be smarter about moving files

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing-inotify#36]
If a file ```f1``` moves from a/f1 to b/f2 we will inform Syncthing twice (i.e. ```scan=a/f1``` and ```scan=b/f1```). This means a rename is not as efficient as it can be since Syncthing can reuse blocks if a move happened within a single scan.

**Comment by Zillode** [comment]
(if we inverse the order of the scans, this would work)

**Comment by Zillode** [comment]
(or we should add ```scan=a/f1&scan2=b/f1``` to the Syncthing API)

**Comment by garagatyi** [comment]
+1

**Comment by Zillode** [comment]
Fixed in upstream and in our beta release.
