### ISSUE TITLE
Exit codes for systemd

### ISSUE THREAD

**Issue by rumpelsepp** [syncthing/syncthing-inotify#39]
The systemd services here suffer from the same problem as the syncthing ones (see here: https://github.com/syncthing/syncthing/pull/1543)

```
Mär 30 01:03:48 naboo systemd[953]: Stopping Syncthing Inotify File Watcher...
Mär 30 01:03:48 naboo systemd[953]: syncthing-inotify.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Mär 30 01:03:48 naboo systemd[953]: Unit syncthing-inotify.service entered failed state.
Mär 30 01:03:48 naboo systemd[953]: syncthing-inotify.service failed.
```

As I don't understand any go code can you please point me to the exit code definitions of syncthing-inotify? I will then create a pull request for the systemd units. :)

**Comment by Zillode** [comment]
Inotify only contains code to return 0. I guess other codes come from go itself when using log.Fatal calls.

**Comment by rumpelsepp** [comment]
Ah. It happens regularly when stopping synthing-inotify:

```
$ systemctl --user stop syncthing-inotify.service
$ systemctl --user status syncthing-inotify.service
● syncthing-inotify.service - Syncthing Inotify File Watcher
   Loaded: loaded (/usr/lib/systemd/user/syncthing-inotify.service; enabled; vendor preset: enabled)
  Drop-In: /home/stefan/.config/systemd/user/syncthing-inotify.service.d
           └─override.conf
   Active: failed (Result: exit-code) since Mi 2015-04-08 07:12:39 CEST; 4s ago
     Docs: https://github.com/syncthing/syncthing-inotify/blob/master/README.md
  Process: 20450 ExecStart=/usr/bin/syncthing-inotify (code=exited, status=2)
 Main PID: 20450 (code=exited, status=2)

Apr 08 07:11:42 alderaan systemd[713]: Starting Syncthing Inotify File Watcher...
Apr 08 07:11:42 alderaan syncthing-inotify[20450]: [OK] 2015/04/08 07:11:42 syncwatcher.go:360: Watching XXX
Apr 08 07:11:42 alderaan syncthing-inotify[20450]: [OK] 2015/04/08 07:11:42 syncwatcher.go:360: Watching XXX
Apr 08 07:11:42 alderaan syncthing-inotify[20450]: [OK] 2015/04/08 07:11:42 syncwatcher.go:360: Watching XXX
Apr 08 07:11:42 alderaan syncthing-inotify[20450]: [OK] 2015/04/08 07:11:42 syncwatcher.go:360: Watching XXX
Apr 08 07:12:39 alderaan systemd[713]: Stopping Syncthing Inotify File Watcher...
Apr 08 07:12:39 alderaan systemd[713]: syncthing-inotify.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 08 07:12:39 alderaan systemd[713]: Stopped Syncthing Inotify File Watcher.
Apr 08 07:12:39 alderaan systemd[713]: Unit syncthing-inotify.service entered failed state.
Apr 08 07:12:39 alderaan systemd[713]: syncthing-inotify.service failed.
```

Does adding 2 to `SuccessExitStatus` make sense here?

**Comment by Zillode** [comment]
Yeah, 0 and 2 mean a clean exit
1 means a fatal error

**Comment by Zillode** [comment]
I'm going to add exit code 3 to indicate inotify requires a restart from it's parent process.

**Comment by rumpelsepp** [comment]
Should be:

```
RestartForceExitStatus=3
```

**Comment by Zillode** [comment]
Should I add this or are you willing to set up a PR?

**Comment by rumpelsepp** [comment]
I am going to make a tour in the mountains in a few minutes. :) So feel free to add it :+1:

**Comment by Zillode** [comment]
The current implementation already restarts on failure [`Restart=on-failure`](https://github.com/syncthing/syncthing-inotify/blob/master/etc/linux-systemd/system/syncthing-inotify%40.service). Am I correct to say that the behavior will not change when adding this line? If not I'll release 0.6.3

**Comment by rumpelsepp** [comment]
Yeah. When you don't add that line, systemd restarts the service; but it considers that an error appeared in the first place. There is also a ticket in the syncthing project about this. I currently can't post a link, since I am on my mobile phone.

On May 24, 2015 12:42:22 PM CEST, Zillode <notifications@github.com> wrote:
>The current implementation already restarts on failure
>[`Restart=on-failure`](https://github.com/syncthing/syncthing-inotify/blob/master/etc/linux-systemd/system/syncthing-inotify%40.service).
>Am I correct to say that the behavior will not change when adding this
>line? If not I'll release 0.6.3
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/syncthing/syncthing-inotify/issues/39#issuecomment-105000596

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rumpelsepp** [comment]
Here it is: https://github.com/syncthing/syncthing/issues/1324

**Comment by Zillode** [comment]
:+1: Thanks! https://github.com/syncthing/syncthing-inotify/commit/8ac71f3a59ef7fa15a9694397eca7f3f551b45aa
