### ISSUE TITLE
Directory Excludes

### ISSUE THREAD

**Issue by majorsl** [syncthing/syncthing-inotify#41]
Would it be a possible enhancement to have directory exclusions? I have a couple of directories where the set interval via SyncThing is just fine.  I suppose, if inotify becomes more closely entwined with the SyncThing GUI someday, it'd be preferable to have that as a sync interval choice.

**Comment by Zillode** [comment]
Dup of https://github.com/syncthing/syncthing-inotify/issues/26
I should make a new release but I'm waiting for upstream to release v0.11 which support multi-scan requests
