### ISSUE TITLE
Higher than average CPU Usage

### ISSUE THREAD

**Issue by majorsl** [syncthing/syncthing-inotify#47]
Running 0.11Beta and the Beta of inotify.  My CPU usage is a constant 17%+ in SyncThing whereas before it was less than 0.1%.  The issue seems to be inotify.  It seems to get stuck in some sort of indexing loop when there is nothing new to index. For example, right now my log is filled with:

[OK] 13:42:42 Syncthing is indexing change in Pictures: [.]
[OK] 13:42:51 Syncthing is indexing change in Pictures: [.]
[OK] 13:43:03 Syncthing is indexing change in Pictures: [.]
[OK] 13:43:12 Syncthing is indexing change in Pictures: [.]
[OK] 13:43:21 Syncthing is indexing change in Pictures: [.]
[OK] 13:43:31 Syncthing is indexing change in Pictures: [.]
[OK] 13:43:40 Syncthing is indexing change in Pictures: [.]

Yet no changes have been made.  That particular share is quite large and probably goes over OS X's max allowed open files, which from what I read was fixed in .6.  In .5, I had just cranked up the max allowed open files and wasn't seeing this issue with the same shares.

If I exit syncthing-inotify and restart, it'll be fine for hours then start getting in a "loop" like the above.

I should mention, even in that "loop" if a change in the directory happens, it will pick it up, so it still does its job.

**Comment by Zillode** [comment]
Could you run inotify with `-verbosity=4`?

**Comment by majorsl** [comment]
Not a problem. It happens fairly randomly, but when it does start, it doesn't see to stop. I'll post back when I see it in action.

**Comment by majorsl** [comment]
The seems to have calmed down to almost normal. I'm beginning to wonder if it had to do with my comment here: https://github.com/syncthing/syncthing/issues/1631

**Comment by Zillode** [comment]
:+1: feel free to reopen when it triggered.
