### ISSUE TITLE
Rest Api System

### ISSUE THREAD

**Issue by cdpb** [syncthing/syncthing-inotify#49]
Hi, 

i tried syncthing-inotify inside a docker container ( debian:jessie base )

```
./syncthing-inotify -target="0.0.0.0:9100" -verbosity="4"

Testing WebGUI
Getting Folders
Status 404 != 200 for GET /rest/system/config:
```

Okay ... But ...

```
curl 0.0.0.0:9100/rest/system/config
404 page not found

curl 0.0.0.0:9100/rest/system
{"alloc": ... }
```

I don't know the syncthing REST API, but it seems like under ```0.0.0.0:9100/rest/system``` is actually the config - or am I wrong ?

BR

cdpb

**Comment by AudriusButkevicius** [comment]
0.0.0.0 is a valid listen address, not a valid connection address.

**Comment by Zillode** [comment]
Also, `/rest/system` is the API for Syncthing <=v0.10.x releases. The latest Syncthing-inotify only works for v0.11 and up.

**Comment by cdpb** [comment]
Okay, same result for 127.0.0.1 and 0.0.0.0.
my syncthing version is v0.10.30
Thank you for help :)

Idea:

syncthing-inotify check if syncthing version <=0.10.x -> exit and error print - to prevent further confusion :+1:
