### ISSUE TITLE
Usage on frontpage (screen!??!)

### ISSUE THREAD

**Issue by ManuelSchneid3r** [syncthing/syncthing-inotify#50]
screen. Really? Just wanted to rant around when I noticed that you provide systemd files. So please update the usage on the frontpage.

**Comment by Zillode** [comment]
Thanks for ranting, PR is welcome

**Comment by ManuelSchneid3r** [comment]
Hmm guess I used the wrong word. Non native speaker, sorry. So will you change it?

**Comment by AudriusButkevicius** [comment]
Probably not, given he said PR's are welcome.

**Comment by ManuelSchneid3r** [comment]
Finally I got it. Though of public relations :D
