### ISSUE TITLE
Error: Status %!d(string=default) != 200 for POST. 403: %!v(MISSING) %!v(MISSING)

### ISSUE THREAD

**Issue by cdpb** [syncthing/syncthing-inotify#51]
Hi,

inotify don't work as expected :) 
syncthing v0.11.1

```
syncthing -no-browser -gui-address="0.0.0.0:9100" -home=/config
syncthing-inotify -target="127.0.0.1:9100" -logflags="4" -verbosity="4"

[TRACE] 08:36:33.399697 Testing WebGUI
[TRACE] 08:36:33.403209 Getting Folders
[DEBUG] 08:36:33.406905 Installing watch for default
[TRACE] 08:36:33.407242 Getting ignore patterns for default
[TRACE] 08:36:33.407683 Requesting STEvents: 0
[OK] 08:36:33.409193 Watching default: /root/Sync
[OK] 08:36:33.409500 The rescan interval of folder default can be increased to 3600 (an hour) or even 86400 (a day) as changes should be observed immediately while syncthing-inotify is running.
```
... okay ...

```
cd /root/Sync
touch 12345

[DEBUG] 08:39:27.375293 Timeout AccumulateChanges
[DEBUG] 08:39:27.375990 Informing about 12345
[TRACE] 08:39:27.376218 Informing ST: default: [12345]
[WARNING] 08:39:27.377220 Error: Status %!d(string=default) != 200 for POST.
403: %!v(MISSING) %!v(MISSING)

```

OS base is Debian Jessie inside Docker Container

Whats wrong ?

Thanks for help

cdpb

**Comment by AudriusButkevicius** [comment]
It seems you have GUI password set up which you are not providing to the inotify utility?

**Comment by cdpb** [comment]
I didn't set a GUI password

**Comment by AudriusButkevicius** [comment]
Are you running syncthing 0.11?

**Comment by cdpb** [comment]
Yes

`syncthing v0.11.1 (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-04-26 11:10:14 UTC`

**Comment by cdpb** [comment]
I tried it with `-api` option and it seems to work.

Maybe update README.md / Using part ?

Just for understanding: Is it nessasary to provide the api key if no password set? I have been thinking that the api key is just a kind of "masked password"

**Comment by calmh** [comment]
The API key is always necessary, although if there's no password set syncthing-inotify could in theory figure it out on it's own...

**Comment by cdpb** [comment]
okay, thanks for clarify.
