### ISSUE TITLE
Add upgrade support

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing-inotify#54]
Add `-upgrade` flag to update the syncthing-inotify client

**Comment by hadogenes** [comment]
You could add deb package and upload to apt.syncthing.net

**Comment by ozra** [comment]
Bump on this one, and meanwhile... see other issue..

**Comment by rumpelsepp** [comment]
And add a switch in the build script to turn it of. Updating this way might break package managers.

**Comment by edrex** [comment]
Isn't this probably going to get rolled into core eventually?

**Comment by lfam** [comment]
See this discussion about putting filesystem notification into the Syncthing executable:
https://github.com/syncthing/syncthing/issues/9

**Comment by edrex** [comment]
yeah, 
> the plan has always been to integrate syncthing-inotify when it works well enough in most case. I think it may be getting there.

**Comment by Zillode** [comment]
Feel welcome to push this a little further. What is still missing is a build script (e.g. https://github.com/syncthing/syncthing-inotify/blob/master/cross-compile.rb) that works on all machines.
At the moment I can only build syncthing-inotify for darwin on an OSX machine. This needs to be fixed such that we can cross-compile it from any machine.
Please continue the discussion here: https://github.com/syncthing/syncthing-inotify/issues/60

**Comment by Zillode** [comment]
Syncthing-inotify is now available in many package managers. Therefore instead of reinventing the wheel, I suggest to close this issue.
 
Debian/Ubuntu:
```
# Add the release PGP keys:
curl -s https://syncthing.net/release-key.txt | sudo apt-key add -

# Add the "release" channel to your APT sources:
echo "deb http://apt.syncthing.net/ syncthing release" | sudo tee /etc/apt/sources.list.d/syncthing.list

# Update and install syncthing:
sudo apt-get update
sudo apt-get install syncthing syncthing-inotify
```

Homebrew OSX: https://github.com/Homebrew/homebrew-core/pull/1293
