### ISSUE TITLE
When syncing, syncthing not sees changes in symlinked folders.

### ISSUE THREAD

**Issue by MasterDimmy** [syncthing/syncthing-inotify#56]
this cannot detect changes in symlinked folders created in windows via "mklink /d" when this occurs.

**Comment by calmh** [comment]
syncthing doesn't follow symlinks. At least [not yet](https://github.com/syncthing/syncthing/issues/1776).

**Comment by CaptainKhan** [comment]
Has that feature been implemented yet? Meaning my thumbs up to the idea.

**Comment by imsodin** [comment]
No, and it wont, see this [statement by calmh in the Syncthing issue](https://github.com/syncthing/syncthing/issues/1776#issuecomment-311612569):

> This has been cooking for a long time and each attempted implementation has run into unanticipated difficulties. Given that and the theoretical difficulties of ensuring correctness in the presence of (followed) symlinks I've decided that following symlinks will not be implemented. I'm also locking this issue because I don't want followup arguing about in the bug tracker. Anyone is welcome to argue about it on the forum, but unless the argument is backed up by a foolproof implementation it's unlikely to have a positive outcome. Sorry, peeps.
