### ISSUE TITLE
No obvious way to tell installed version

### ISSUE THREAD

**Issue by ozra** [syncthing/syncthing-inotify#57]
I tried `--version` - no go. I can't see it when starting.
Might be that I'm blind, but otherwise, it'd be good to quickly tell if you're at the last version or not.
Obviously #54 would be ideal.

**Comment by jpjp** [comment]
$ ~/bin/syncthing/syncthing --version
syncthing v0.11.5 (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-05-15 08:46:47 UTC
