### ISSUE TITLE
Crash when trying to run the compiled binary

### ISSUE THREAD

**Issue by 0xACE** [syncthing/syncthing-inotify#58]
Hey, I just tried the binary provided in syncthing-inotify-linux-386-v0.6.1.tar.gz

Running the file results in:

    $ syncthing-inotify
    SIGILL: illegal instruction
    PC=0x82169f9
    
    goroutine 1 [running, locked to thread]:
    math.init·1()
    	/Users/lhoste/Libs/go/src/math/pow10.go:34 +0x19 fp=0x1861b748 sp=0x1861b744
    math.init()
    	/Users/lhoste/Libs/go/src/math/unsafe.go:21 +0x3f fp=0x1861b74c sp=0x1861b748
    strconv.init()
    	/Users/lhoste/Libs/go/src/strconv/quote.go:455 +0x45 fp=0x1861b768 sp=0x1861b74c
    io/ioutil.init()
    	/Users/lhoste/Libs/go/src/io/ioutil/tempfile.go:95 +0x4a fp=0x1861b788 sp=0x1861b768
    github.com/rjeczalik/notify.init()
    	/Users/lhoste/tmp/go-workspace/src/github.com/rjeczalik/notify/watchpoint_other.go:23 +0x5e fp=0x1861b7b0 sp=0x1861b788
    main.init()
    	/Users/lhoste/tmp/go-workspace/src/github.com/syncthing/syncthing-inotify/syncwatcher.go:940 +0x45 fp=0x1861b7cc sp=0x1861b7b0
    runtime.main()
    	/Users/lhoste/Libs/go/src/runtime/proc.go:58 +0xbd fp=0x1861b7f0 sp=0x1861b7cc
    runtime.goexit()
    	/Users/lhoste/Libs/go/src/runtime/asm_386.s:2287 +0x1 fp=0x1861b7f4 sp=0x1861b7f0
    
    goroutine 2 [runnable]:
    runtime.forcegchelper()
    	/Users/lhoste/Libs/go/src/runtime/proc.go:90
    runtime.goexit()
    	/Users/lhoste/Libs/go/src/runtime/asm_386.s:2287 +0x1
    
    goroutine 3 [runnable]:
    runtime.bgsweep()
    	/Users/lhoste/Libs/go/src/runtime/mgc0.go:82
    runtime.goexit()
    	/Users/lhoste/Libs/go/src/runtime/asm_386.s:2287 +0x1
    
    goroutine 4 [runnable]:
    runtime.runfinq()
    	/Users/lhoste/Libs/go/src/runtime/malloc.go:712
    runtime.goexit()
    	/Users/lhoste/Libs/go/src/runtime/asm_386.s:2287 +0x1
    
    eax     0x1860a0e8
    ebx     0x843cd6c
    ecx     0x186000a0
    edx     0x843d168
    edi     0x0
    esi     0x37f8
    ebp     0x8367380
    esp     0x1861b744
    eip     0x82169f9
    eflags  0x10206
    cs      0x73
    fs      0x0
    gs      0x3f

(Note that this accidentally was posted before I could complete the bug report, incase anyone only subscribes to this by e-mail, they've not noticed the changes, most likely)

**Comment by AudriusButkevicius** [comment]
Can you providw your processor type, kernel version?

**Comment by 0xACE** [comment]
OS/Kernel:

    Linux 4.0.3-1-ARCH #1 SMP PREEMPT i686 GNU/Linux

CPU information:

    processor       : 0
    vendor_id       : AuthenticAMD
    cpu family      : 6
    model           : 8
    model name      : AMD Sempron(tm)   2600+
    stepping        : 1
    cpu MHz         : 1835.769
    cache size      : 256 KB
    physical id     : 0
    siblings        : 1
    core id         : 0
    cpu cores       : 1
    apicid          : 0
    initial apicid  : 0
    fdiv_bug        : no
    f00f_bug        : no
    coma_bug        : no
    fpu             : yes
    fpu_exception   : yes
    cpuid level     : 1
    wp              : yes
    flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 mmx fxsr sse syscall mp mmxext 3dnowext 3dnow vmmcall
    bugs            : fxsave_leak
    bogomips        : 3673.51
    clflush size    : 32
    cache_alignment : 32
    address sizes   : 34 bits physical, 32 bits virtual
    power management: ts

**Comment by 0xACE** [comment]
Atm, I don't have a machine which can compile this project. Therefor I cannot test 68522d2.

Does anyone know when I can expect a compiled binary ?

**Comment by Zillode** [comment]
@0xACE try http://wilma.vub.ac.be/~lhoste/syncthing/unofficial/syncthing-inotify-windows-386-v0.6.1.tar.gz

**Comment by 0xACE** [comment]
I'm on linux, doubt that binary would work...

**Comment by Zillode** [comment]
http://wilma.vub.ac.be/~lhoste/syncthing/unofficial/syncthing-inotify-linux-386-v0.6.1.tar.gz

**Comment by 0xACE** [comment]
Hey, I just tried running the compiled binary you provided, it crashes too:

    $ ./syncthing-inotify
    SIGILL: illegal instruction
    PC=0x82170b9
    
    goroutine 1 [running, locked to thread]:
    math.init·1()
            /Users/lhoste/Libs/go/src/math/pow10.go:34 +0x19 fp=0x1861b748 sp=0x1861b744
    math.init()
            /Users/lhoste/Libs/go/src/math/unsafe.go:21 +0x3f fp=0x1861b74c sp=0x1861b748
    strconv.init()
            /Users/lhoste/Libs/go/src/strconv/quote.go:455 +0x45 fp=0x1861b768 sp=0x1861b74c
    io/ioutil.init()
            /Users/lhoste/Libs/go/src/io/ioutil/tempfile.go:95 +0x4a fp=0x1861b788 sp=0x1861b768
    github.com/zillode/notify.init()
            /Users/lhoste/tmp/go-workspace/src/github.com/zillode/notify/watchpoint_other.go:23 +0x5e fp=0x1861b7b0 sp=0x1861b788
    main.init()
            /Users/lhoste/tmp/go-workspace/src/github.com/syncthing/syncthing-inotify/syncwatcher.go:967 +0x45 fp=0x1861b7cc sp=0x1861b7b0
    runtime.main()
            /Users/lhoste/Libs/go/src/runtime/proc.go:58 +0xbd fp=0x1861b7f0 sp=0x1861b7cc
    runtime.goexit()
            /Users/lhoste/Libs/go/src/runtime/asm_386.s:2287 +0x1 fp=0x1861b7f4 sp=0x1861b7f0
    
    goroutine 2 [runnable]:
    runtime.forcegchelper()
            /Users/lhoste/Libs/go/src/runtime/proc.go:90
    runtime.goexit()
            /Users/lhoste/Libs/go/src/runtime/asm_386.s:2287 +0x1
    
    goroutine 3 [runnable]:
    runtime.bgsweep()
            /Users/lhoste/Libs/go/src/runtime/mgc0.go:82
    runtime.goexit()
            /Users/lhoste/Libs/go/src/runtime/asm_386.s:2287 +0x1
    
    goroutine 4 [runnable]:
    runtime.runfinq()
            /Users/lhoste/Libs/go/src/runtime/malloc.go:712
    runtime.goexit()
            /Users/lhoste/Libs/go/src/runtime/asm_386.s:2287 +0x1
    
    eax     0x1860a0e8
    ebx     0x843dd8c
    ecx     0x186000a0
    edx     0x843e188
    edi     0x0
    esi     0x37f8
    ebp     0x8368784
    esp     0x1861b744
    eip     0x82170b9
    eflags  0x10206
    cs      0x73
    fs      0x0
    gs      0x3f


I should mention that the compiled 386 binary provided by the `syncthing` github page runs fine on this machine. Therefore running syncthing-inotify should be possible.

**Comment by calmh** [comment]
@Zillode is the standard library also built with GO386=387?
