### ISSUE TITLE
Depends on CGO and platform specific libraries

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing-inotify#60]
Syncthing-inotify relies on `darwin_amd64/notify.a` and CGO to enable efficient FSEvent handlers on OSX. Therefore, if we include this package in the core, we reduce cross-platform compilation compatibility and (probably) need to update the Syncthing build process.

**Comment by AudriusButkevicius** [comment]
I think cross compiling works fine as long as you have the OS X object files available in the right directory on Linux, because linking to the system libraries is done at run time not at compile time.

**Comment by Zillode** [comment]
I'm more concerned about including a closed-source blob in the main repo (ping @calmh). Also the notify library is incompatible with solaris and darwin-386, which is not a too big deal if we update the build scripts with some exclude patterns.

**Comment by Zillode** [comment]
It's not only the binary blob, it also requires all CoreFoundation header files

**Comment by AudriusButkevicius** [comment]
Last I checked there was a project (xgo or maybe some other similar) which solves that problem exactly, by providing the relevant headers in the relevant places.

**Comment by Zillode** [comment]
Fixed by https://github.com/syncthing/syncthing-inotify/commit/5c9c17a835821162ac4d3c337abe9575d2755571
