### ISSUE TITLE
Feature request: ability to allow certain folders to sync without WiFi

### ISSUE THREAD

**Issue by 0xACE** [syncthing/syncthing-inotify#61]
Hey, I have a feature that I miss.

I've got 2 folders synced to my cellphone:

1. Music
2. Other

In my case, the `Music` folder performs very huge changes frequently (today I transfered 700MB) where I copied music to the cellphone, I don't ever want that folder to sync outside my WiFi as I will hit my datacap really fast this way.

In the `Other` folder, I sync minor things, such as small text documents or screenshots of a product from a store or something. Since these changes are small, I don't mind if I sync it outside the WiFi network, as the changes will most likely never reach my datacap.

Is this something I can expect to be implemented in the app?

**Comment by Zillode** [comment]
I think this is https://github.com/syncthing/syncthing-android/issues/254 ?

**Comment by 0xACE** [comment]
No, #254 is talking about pausing a ongoing synchronization process.

I'm talking about a filter which decides which folders to sync while the cellphone is only using the network data.

**Comment by Zillode** [comment]
I still think it is the same? This issue is unrelated to inotify anyway.

**Comment by 0xACE** [comment]
>This issue is unrelated to inotify anyway.
Sorry, I must've mixed tabs.

>I still think it is the same?
If you see it that way, I don't mind if you close this issue.

Again, sorry for posting this to the wrong repository.
