### ISSUE TITLE
Couldn't find in Documentation - set "rescan intervall" in Syncthing to 0

### ISSUE THREAD

**Issue by schuft69** [syncthing/syncthing-inotify#63]
Is it needed to set "rescan intervall" in Syncthing to 0 (per folder) or will syncthing-inotify do this for me?

Found nothing about that in the documentation..

**Comment by Zillode** [comment]
Syncthing-inotify will do this for you, as long as it's running. Added to the wiki: https://github.com/syncthing/syncthing-inotify/wiki#extending-the-rescan-interval-of-syncthing
