### ISSUE TITLE
systemd service file doesn't work

### ISSUE THREAD

**Issue by lfam** [syncthing/syncthing-inotify#66]
The systemd service file that's currently in HEAD doesn't work on Debian 8.1. It seems to choke on the filesystem protection directives ProtectHome and ProtectSystem. I don't fully understand these directives but it seems like they should be compatible with an inotify watcher if their values are set to read-only, which is true in my case because I'm only watching under ```/home``` (ProtectSystem is set to Full, as in HEAD). I have no problems if I comment out both directives. Commenting out either one still fails.

Some info:
```
$ systemd --version
systemd 215
+PAM +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ -SECCOMP -APPARMOR
$ ls -l `which syncthing-inotify`
lrwxrwxrwx 1 root staff 36 Jun  6 20:51 /usr/local/bin/syncthing-inotify -> syncthing-inotify-linux-amd64-v0.6.4

```

I try to use the syncthing-inotify.service file in git commit 8ac71f3.
link: https://github.com/syncthing/syncthing-inotify/blob/8ac71f3a59ef7fa15a9694397eca7f3f551b45aa/etc/linux-systemd/user/syncthing-inotify.service
```
$ systemctl --user restart syncthing-inotify; systemctl --user status syncthing-inotify
● syncthing-inotify.service - Syncthing Inotify File Watcher
   Loaded: loaded (/etc/systemd/user/syncthing-inotify.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2015-06-16 23:16:30 EDT; 7ms ago
     Docs: https://github.com/syncthing/syncthing-inotify/blob/master/README.md
  Process: 1412 ExecStart=/usr/bin/syncthing-inotify -logflags=0 (code=exited, status=226/NAMESPACE)
 Main PID: 1412 (code=exited, status=226/NAMESPACE)

Jun 16 23:16:30 hostname systemd[1061]: syncthing-inotify.service: main process exited, code=exited, status=226/NAMESPACE
Jun 16 23:16:30 hostname systemd[1061]: Unit syncthing-inotify.service entered failed state.
```

And here is the full log from journald. It seems to restart itself several times. I have no idea why it stops.
```
$ journalctl --user-unit syncthing-inotify -f
Jun 16 23:16:30 hostname systemd[1061]: Starting Syncthing Inotify File Watcher...
Jun 16 23:16:30 hostname systemd[1061]: Started Syncthing Inotify File Watcher.
Jun 16 23:16:30 hostname systemd[1061]: syncthing-inotify.service: main process exited, code=exited, status=226/NAMESPACE
Jun 16 23:16:30 hostname systemd[1061]: Unit syncthing-inotify.service entered failed state.
Jun 16 23:16:30 hostname systemd[1061]: syncthing-inotify.service holdoff time over, scheduling restart.
Jun 16 23:16:30 hostname systemd[1061]: Stopping Syncthing Inotify File Watcher...
Jun 16 23:16:30 hostname systemd[1061]: Starting Syncthing Inotify File Watcher...
Jun 16 23:16:30 hostname systemd[1061]: Started Syncthing Inotify File Watcher.
Jun 16 23:16:30 hostname systemd[1061]: syncthing-inotify.service: main process exited, code=exited, status=226/NAMESPACE
Jun 16 23:16:30 hostname systemd[1061]: Unit syncthing-inotify.service entered failed state.
Jun 16 23:16:30 hostname systemd[1061]: syncthing-inotify.service holdoff time over, scheduling restart.
Jun 16 23:16:30 hostname systemd[1061]: Stopping Syncthing Inotify File Watcher...
Jun 16 23:16:30 hostname systemd[1061]: Starting Syncthing Inotify File Watcher...
Jun 16 23:16:30 hostname systemd[1061]: Started Syncthing Inotify File Watcher.
Jun 16 23:16:30 hostname systemd[1061]: syncthing-inotify.service: main process exited, code=exited, status=226/NAMESPACE
Jun 16 23:16:30 hostname systemd[1061]: Unit syncthing-inotify.service entered failed state.
Jun 16 23:16:30 hostname systemd[1061]: syncthing-inotify.service holdoff time over, scheduling restart.
Jun 16 23:16:30 hostname systemd[1061]: Stopping Syncthing Inotify File Watcher...
Jun 16 23:16:30 hostname systemd[1061]: Starting Syncthing Inotify File Watcher...
Jun 16 23:16:30 hostname systemd[1061]: Started Syncthing Inotify File Watcher.
Jun 16 23:16:30 hostname systemd[1061]: syncthing-inotify.service: main process exited, code=exited, status=226/NAMESPACE
Jun 16 23:16:30 hostname systemd[1061]: Unit syncthing-inotify.service entered failed state.
Jun 16 23:16:31 hostname systemd[1061]: syncthing-inotify.service holdoff time over, scheduling restart.
Jun 16 23:16:31 hostname systemd[1061]: Stopping Syncthing Inotify File Watcher...
Jun 16 23:16:31 hostname systemd[1061]: Starting Syncthing Inotify File Watcher...
Jun 16 23:16:31 hostname systemd[1061]: Started Syncthing Inotify File Watcher.
Jun 16 23:16:31 hostname systemd[1061]: syncthing-inotify.service: main process exited, code=exited, status=226/NAMESPACE
Jun 16 23:16:31 hostname systemd[1061]: Unit syncthing-inotify.service entered failed state.
Jun 16 23:16:31 hostname systemd[1061]: syncthing-inotify.service holdoff time over, scheduling restart.
Jun 16 23:16:31 hostname systemd[1061]: Stopping Syncthing Inotify File Watcher...
Jun 16 23:16:31 hostname systemd[1061]: Starting Syncthing Inotify File Watcher...
Jun 16 23:16:31 hostname systemd[1061]: syncthing-inotify.service start request repeated too quickly, refusing to start.
Jun 16 23:16:31 hostname systemd[1061]: Failed to start Syncthing Inotify File Watcher.
Jun 16 23:16:31 hostname systemd[1061]: Unit syncthing-inotify.service entered failed state.
```

**Comment by Zillode** [comment]
@rumpelsepp any idea?

**Comment by rumpelsepp** [comment]
Just a wild guess, have you tried copying the syncthing-inotify binary to `/usr/local/bin/` instead? As far as I can see you have symlinked it to your homedir. Since these ReadOnly options mount separate instances of `/usr` and `/home` for the service, I guess symlinks from one special instance to another might cause the problem.

**Comment by lfam** [comment]
The binary is at ```/usr/bin/syncthing-inotify```.

**Comment by lfam** [comment]
Um... so I made a mistake before, but it doesn't seem to have caused the problem. I forgot to change the path in the service file from ```/usr/bin``` to ```/usr/local/bin```. I get the same result with the correct path. I guess this means that the service is failing before systemd even tries to exec the binary.

And the symlink is a local symlink. The target is in ```/usr/local/bin```.

	$ systemctl --user restart syncthing-inotify; systemctl --user status syncthing-inotify
	● syncthing-inotify.service - Syncthing Inotify File Watcher
	   Loaded: loaded (/etc/systemd/user/syncthing-inotify.service; enabled)
	   Active: activating (auto-restart) (Result: exit-code) since Wed 2015-06-17 16:19:58 EDT; 5ms ago
	     Docs: https://github.com/syncthing/syncthing-inotify/blob/master/README.md
	  Process: 8370 ExecStart=/usr/local/bin/syncthing-inotify -logflags=0 (code=exited, status=226/NAMESPACE)
	 Main PID: 8370 (code=exited, status=226/NAMESPACE)
	
	Jun 17 16:19:58 hostname systemd[1061]: Starting Syncthing Inotify File Watcher...
	Jun 17 16:19:58 hostname systemd[1061]: Started Syncthing Inotify File Watcher.
	Jun 17 16:19:58 hostname systemd[1061]: syncthing-inotify.service: main process exited, code=exited, status=226/NAMESPACE
	Jun 17 16:19:58 hostname systemd[1061]: Unit syncthing-inotify.service entered failed state.

**Comment by lfam** [comment]
I'm going to investigate https://github.com/syncthing/syncthing-inotify/issues/67. Although like I said in my last post, systemd doesn't even seem to try to exec the binary before failing.

**Comment by lfam** [comment]
And in case you are wondering what my working unit file looks like, here it is.
```
[Unit]
Description=Syncthing Inotify File Watcher
Documentation=https://github.com/syncthing/syncthing-inotify/blob/master/README.md
PartOf=syncthing.service

[Service]
ExecStart=/usr/local/bin/syncthing-inotify -logflags=0
SuccessExitStatus=2
RestartForceExitStatus=3
Restart=on-failure
;ProtectSystem=full
;ProtectHome=read-only

[Install]
WantedBy=syncthing.service
```

**Comment by lfam** [comment]
Never mind. I don't think these directives work at all on my system.

**Comment by rumpelsepp** [comment]
Your install section should be (for user unit):

```
[Install]
WantedBy=default.target
```
and

```
[Install]
WantedBy=multi-user.target
```

for the system unit. I think you have tried starting this unit with 

```
# systemctl start syncthing-inotify.service
```

That does not work, since it seems to be the user unit. Try

```
$ systemctl --user start syncthing-inotify.service
```

instead, and fix your install section.

**Comment by lfam** [comment]
That's okay! I see the mistakes you mentioned ALL over the internet. It seems that everyone has to make this mistake, and I did also, at one point ;)

**Comment by rumpelsepp** [comment]
:+1:

**Comment by herrernst** [comment]
I have a Debian 8 (not upgraded from 7) and a fresh installation of syncthing from your repos, and I also get this error when starting a user unit for syncthing-inotify. I have systemd 215-17+deb8u7, and according to the Debian bug tracker this should be fixed with systemd/215-17+deb8u3. If it matters, I'm on armhf.
