### ISSUE TITLE
Rescan interval not returning to config value upon exit

### ISSUE THREAD

**Issue by SenorLoco** [syncthing/syncthing-inotify#69]
I'm using syncthing-inotify v0.6.5 and syncthing v11.10 and noticed an issue with the delay-scan option.  The option itself works great, but the issue I've noticed comes when syncthing-inotify stops running (which is very rare :+1: ) Within syncthing I have the rescan interval set at the default 60 seconds but if inotify stops running syncthing doesn't start syncing every 60 seconds again.  I guessing that if I were to wait 1 day things would start syncing every 60 seconds again, but having things not syncing for 24 hours if I were to not noticed inotify wasn't running could cause issues :)

**Comment by lfam** [comment]
How are you supervising the processes? I would tell the supervisor to restart Syncthing if syncthing-inotify exits.

**Comment by Zillode** [comment]
Good point, a rescan delay of 1h would be a better default.
@lfam's solution would also work
