### ISSUE TITLE
Random files being ignored

### ISSUE THREAD

**Issue by jeremejevs** [syncthing/syncthing-inotify#71]
I haven't done a proper research, but my Syncthing-inotify instance seems to be ignoring the addition of some files. I've tried two different `.mkv` files (~1GB each) and one `.iso` (~600MB), all three got ignored (waited several minutes after each). Then I tried an `.img` file (~2GB) - it was noticed immediately. Removed it and tried again - no problems. A few random small textual / binary files worked fine too. Tried re-adding the `.iso` file - no change, still ignored.

I'm running Syncthing GTK on Windows, "Monitor filesystem for changes" is enabled, "Rescan Interval" is set to 1 hour.

**Comment by Zillode** [comment]
Run inotify with `-verbosity 4` and try again. It should say if it ignored the changes.

**Comment by jeremejevs** [comment]
```
[DEBUG] 00:19:09 Change detected in: D:\syncthing\XenServer-6.5.0-xenserver.org-install-cd.iso (could still be ignored)
[TRACE] 00:19:09 Change detected in: D:\syncthing\XenServer-6.5.0-xenserver.org-install-cd.iso
[DEBUG] 00:19:09 Change detected in: D:\syncthing\XenServer-6.5.0-xenserver.org-install-cd.iso (could still be ignored)
[TRACE] 00:19:09 Change detected in: D:\syncthing\XenServer-6.5.0-xenserver.org-install-cd.iso
[DEBUG] 00:19:09 [FS] Incoming Changes for default, speeding up inotify timeout parameters
[DEBUG] 00:19:09 [FS] Tracking: XenServer-6.5.0-xenserver.org-install-cd.iso
[DEBUG] 00:19:09 [FS] Incoming Changes for default, speeding up inotify timeout parameters
[DEBUG] 00:19:09 [FS] Tracking: XenServer-6.5.0-xenserver.org-install-cd.iso
[DEBUG] 00:19:09 Timeout AccumulateChanges
[DEBUG] 00:19:09 Informing about XenServer-6.5.0-xenserver.org-install-cd.iso
[TRACE] 00:19:09 Informing ST: default: [XenServer-6.5.0-xenserver.org-install-cd.iso]
[TRACE] 00:19:09 Requesting STEvents: 428
[TRACE] 00:19:09 Requesting STEvents: 429
[OK] 00:19:09 Syncthing is indexing change in default: [XenServer-6.5.0-xenserver.org-install-cd.iso]
[DEBUG] 00:19:09 [INFORMED] Removed tracking for XenServer-6.5.0-xenserver.org-install-cd.iso
[TRACE] 00:19:09 Requesting STEvents: 431
[DEBUG] 00:19:10 Slowing down inotify timeout parameters for default
```

No reaction from the client, of course.

**Comment by Zillode** [comment]
I don't know why it would miss the changes. Everything is tracked properly and Syncthing replies 'ok'
```
[OK] 00:19:09 Syncthing is indexing change in default: [XenServer-6.5.0-xenserver.org-install-cd.iso]
```
The problem is probably found in Syncthing itself. Could you run Syncthing with ```STTRACE=model,scanner ./syncthing```? (see the [docs](http://docs.syncthing.net/dev/debugging.html))

**Comment by jeremejevs** [comment]
Okay, looks like ST receives the rescan command from ST-inotify too early (while the file is still locked by the system, I guess) and fails to open it, and then doesn't attempt to open it later.

```
[P5LJN] 2015/06/25 15:35:14.024109 walk.go:87: DEBUG: Walk \\?\D:\syncthing [XenServer-6.5.0-xenserver.org-install-cd.iso] 131072 &{[] true 0xc082220d60 d41d8cd98f00b204e9800998ecf8427e 0xc08210e660 0xc0821142a0}
[P5LJN] 2015/06/25 15:35:14.024109 walk.go:373: DEBUG: checkDir \\?\D:\syncthing &{syncthing {16 {161291648 30453375} {1643797893 30453571} {1643797893 30453571} 0 4096} {0 0} \\?\D:\syncthing 0 0 0}
[P5LJN] 2015/06/25 15:35:14.024109 walk.go:342: DEBUG: rescan: File{Name:"XenServer-6.5.0-xenserver.org-install-cd.iso", Flags:010644, Modified:1424006898, Version:[{9175687024390728045 2}], Size:128, Blocks:[]} 1435235713 -rw-rw-rw-
[P5LJN] 2015/06/25 15:35:14.024109 walk.go:358: DEBUG: to hash: \\?\D:\syncthing\XenServer-6.5.0-xenserver.org-install-cd.iso File{Name:"XenServer-6.5.0-xenserver.org-install-cd.iso", Flags:0644, Modified:1435235713, Version:[{9175687024390728045 3}], Size:0, Blocks:[]}
[P5LJN] 2015/06/25 15:35:14.024109 blockqueue.go:43: DEBUG: open: open \\?\D:\syncthing\XenServer-6.5.0-xenserver.org-install-cd.iso: The process cannot access the file because it is being used by another process.
[P5LJN] 2015/06/25 15:35:14.024109 blockqueue.go:70: DEBUG: hash error: XenServer-6.5.0-xenserver.org-install-cd.iso open \\?\D:\syncthing\XenServer-6.5.0-xenserver.org-install-cd.iso: The process cannot access the file because it is being used by another process.
```

This should probably be moved to Syncthing issues, right?

**Comment by AudriusButkevicius** [comment]
The the file seems to be opened exclusively by something else (daemon tools? some other utility?) which is preventing syncthing from opening it. I don't think there is anything syncthing can do to change this.

**Comment by jeremejevs** [comment]
@AudriusButkevicius I don't have any disk drive emulators, and this file is just being copied there, not moved/modified. I don't know, maybe it's Windows Defender doing a quick signature check on it, but that's a normal thing. I don't have any anti-virus software. Just tried an `.mkv` again - same issue (and what's worse, the existing `.img`, which was ignored earlier, was still ignored, even though the rescan was triggered).

**Comment by AudriusButkevicius** [comment]
Well, I am not sure who's responsibility this should technically be.

Perhaps syncthing should return an error if the scan fails to hash one of the files, but the amount of boilerplate code that would need (due to hashing happening in its own routine, and walking in another routine, and gui in a third routine) is alot.

**Comment by jeremejevs** [comment]
From what I can tell, Syncthing-inotify aggregates the changes, so it must be waiting for some time before asking Syncthing to rescan. Also, I've taken a look at Inotify itself, and looks like it would normally fire three events for a a file being copied: `IN_CREATE`, `IN_OPEN` and `IN_CLOSE_*`. Could the copying process takes so long (say, 5 seconds), that Syncthing-inotify aggregator assumes nothing else is going to happen after `IN_OPEN`, and asks Syncthing to do a rescan, while the file is still locked by the system? And then, when the `IN_CLOSE` event finally arrives, Syncthing-inotify simply discards it, since it thinks Syncthing was already asked to do a rescan?

Don't want to spend hours figuring out the code, surely you guys know it better than me, and can confirm / deny my hypothesis.

**Comment by lfam** [comment]
Reading this, I am reminded that inotify drops or misses events in some cases. This means that you need to scan periodically. If syncthing-inotify keeps delaying syncthing's scan, then Syncthing will never pick up the change.

**Comment by AudriusButkevicius** [comment]
Well if the kernel can't provide you with a reliable stream of events, then they shouldn't offer the functionality to start with, because how are people expected to use this instead of scanning, if this is unreliable?

**Comment by jeremejevs** [comment]
It does work properly in this case, though.

**Comment by AudriusButkevicius** [comment]
Agree, still, not sure how to solve this.
It would be interesting to see what @Zillode and perhaps even @calmh thinks.

**Comment by Zillode** [comment]
I think it is possible, but pretty hard to trigger.
Case 1: `IN_OPEN` happens, we inform Syncthing. Afterwards we receive the `IN_CLOSE` event and we inform Syncthing again. This is OK.
Case 2: We aggregate `IN_OPEN` and `IN_CLOSE`. This is OK.
Case 3: We inform Syncthing about the `IN_OPEN` event. During this call to the rest API, the `IN_CLOSE` happens just a bit after Syncthing tried to scan the file and just before we receive the scan results. This window is pretty narrow, unless many (other) files need to be scanned as well. This is not OK.

I'll label this as a bug. I also have a solution in mind that would capture case 3.

**Comment by jeremejevs** [comment]
Maybe the window isn't as small as it appears, if a file is blocked, when Syncthing attempts to open it. I couldn't find any docs supporting this, but maybe there's some timeout in `os.Open` for locked files? Or maybe it doesn't return immediately, because the system is still busy writing to that file.

**Comment by AudriusButkevicius** [comment]
I am sure it returns immediately, as the os.Open semantics follow the OS equivalent, which probably just returns an error.

**Comment by Zillode** [comment]
_if_ Syncthing returns an error when the scan fails, inotify will resubmit the scan request at a later point in time.

**Comment by Zillode** [comment]
@jeremejevs Could you try again with syncthing-inotify [v0.7](https://github.com/syncthing/syncthing-inotify/releases/tag/v0.7)? @tillberg made some improvements related to this.

**Comment by jeremejevs** [comment]
@Zillode Sorry, haven't used Syncthing ever since, but I'll give it a go next time I get a breather.
