### ISSUE TITLE
use of closed network connection

### ISSUE THREAD

**Issue by jangrewe** [syncthing/syncthing-inotify#72]
Thanks for creating syncthing-inotify, it's much better than having the disks in your NAS every hour even if there's nothing to sync! =)

I do have an issue with notifying syncthing on changes, though. The following shows up in the log all the time:

```
[WARNING] 17:16:38 Failed to perform request Post http://0.0.0.0:8384/rest/db/scan?folder=backups&next=86400&sub=JANdroidOne%2FAndroid%2Fdata%2Fcom.boxer.email%2Ffiles%2Fring_log: read tcp 127.0.0.1:8384: use of closed network connection
[WARNING] 17:16:38 Syncthing failed to index changes for  backups Post http://0.0.0.0:8384/rest/db/scan?folder=backups&next=86400&sub=JANdroidOne%2FAndroid%2Fdata%2Fcom.boxer.email%2Ffiles%2Fring_log: read tcp 127.0.0.1:8384: use of closed network connection
```

**Comment by AudriusButkevicius** [comment]
Not sure if it's you or inotify, but the address for syncthing is not correct.
It should probably be 127.0.0.1 and not 0.0.0.0

**Comment by jangrewe** [comment]
Ah, that could be the reason. I've set the GUI port to use 0.0.0.0 and didn't pay attention that syncthing-inotify uses the same config.xml ... that should be a quick fix then, thanks.

**Comment by jangrewe** [comment]
Hmm, looks like i was wrong... I've told syncthing-inotify to use ```http://192.168.0.2:8384/``` as the target, but still get:
```
[WARNING] 17:44:23 Failed to perform request Post http://192.168.0.2:8384/rest/db/scan?folder=backups&next=86400&sub=.stfolder: read tcp 192.168.0.2:8384: use of closed network connection
```
It's definitely the right address, because:
```
curl -X POST 'http://192.168.0.2:8384/rest/db/scan?folder=backups&next=86400&sub=.stfolder'
Not Authorized
```

**Comment by Zillode** [comment]
Try `127.0.0.1`, or `https://127.0.0.1:8384` please.
Note that a ip addresses, e.g. `10.211.55.12`, also work for me.

**Comment by jangrewe** [comment]
```192.168.0.2``` is a local IP, too - just in Class C instead of Class B ;-)

But ```127.0.0.1``` still results in
´´´
[WARNING] 23:27:42 Failed to perform request Post http://127.0.0.1:8384/rest/db/scan?folder=mp3&next=86400&sub=.stfolder: read tcp 127.0.0.1:8384: use of closed network connection
´´´
so neither localhost nor the actual IP on of the NIC work for me.

**Comment by AudriusButkevicius** [comment]
Does the call work via the browser/curl? 
Try https not only http

Though the error implies that inotify closed the socket and then tried writing/reading from it.

**Comment by jangrewe** [comment]
For each IP and both HTTP and HTTPS i always get "Not Authorized" when trying one of these URLs per curl, so that tells me that the GUI would respond as expected - if the client wouldn't close its socket too soon :D

**Comment by calmh** [comment]
Is the "use of closed network connection" an occasional thing? If so, it's an effect of HTTP keepalives and should just be retried on the client side. (That is, the client needs to catch this error and retry, or disable keepalives to start with.)

**Comment by Zillode** [comment]
Keepalives are disabled: https://github.com/syncthing/syncthing-inotify/blob/fa6ba15cbdfab99efc3d5ce26e711266c8ff0402/syncwatcher.go#L494

@jangrewe: Could you try with the API key in curl (```--header "X-API-Key: 123" ```) just to definitely rule out other issues?

**Comment by jangrewe** [comment]
@Zillode if i send the API key along, it works fine.

```
curl -k -X POST -H 'X-API-key: yaddayadda' 'http://127.0.0.1:8384/rest/db/scan?folder=default&next=86400&sub=.stfolder'
```
Then i can see the status change to "Scanning" in the GUI.

**Comment by francoism90** [comment]
I'm also facing this issue: `Cannot connect to Syncthing: Get http://0.0.0.0:8384/rest/404: dial tcp 0.0.0.0:8384: getsockopt: connection refuse`

Should this not be: `dial tcp 0.0.0.0:22000`?

**Comment by AudriusButkevicius** [comment]
No. That implies syncthing is down.

**Comment by francoism90** [comment]
@AudriusButkevicius .. sorry configuration error. Everything is working fine now on 0.0.0.0. :)
