### ISSUE TITLE
Issue running inside tmux

### ISSUE THREAD

**Issue by Wicked0ne** [syncthing/syncthing-inotify#73]
I'm experiencing a very weird issue while using syncthing-inotify on FreeBSD 10.1. I use tmux instead of screen and when I start syncthing-inotify while I'm connected to a tmux session, as soon as it starts the system becomes almost unresponsive. Switching panes in tmux takes around 10 seconds. The system load does go up(saw it as high as 5 or 6). As soon as I ctrl+c to close syncthing-inotify things go back to normal. I opened up another ssh session and started syncthing-inotify while not using tmux and it seems to work as expected. I also noticed that tmux's cpu usage spikes to 100% as soon as syncthing-inotify is started.

Software versions:
./syncthing --version
syncthing v0.11.11 (go1.4.2 freebsd-amd64 default) unknown-user@syncthing-builder 2015-06-28 19:10:57 UTC

./syncthing-inotify --version
syncthing-inotify v0.6.5 (go1.4.2 freebsd-amd64)

tmux -V
tmux 2.0

zsh --version
zsh 5.0.8 (amd64-portbld-freebsd10.1)

uname -a
FreeBSD Cerberus 10.1-RELEASE-p10 FreeBSD 10.1-RELEASE-p10 #0: Wed May 13 06:54:13 UTC 2015     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

I'm not sure what else might be of use here but will be happy to provide any additional information as needed.

**Comment by Zillode** [comment]
Sorry I cannot reproduce this in linux using tmux. The only thing I can think of is that you exhausted the kqueue open file handlers?

**Comment by Zillode** [comment]
Closing due to lack of feedback.
Please comment/reopen if this is still an issue.
