### ISSUE TITLE
Illegal Instruction on OSX 10.7.5

### ISSUE THREAD

**Issue by mikh3x4** [syncthing/syncthing-inotify#74]
I'm trying to set up syncthing-inotify on my mac. I downloaded the darwin_amd64 verison and followed the instructions to "Run and hide on unix in a screen"

screen -S inotify -dm ./syncthing-inotify

Later checking with screen -ls the previous command didn't create a new screen. I also checked that after running the command the sync only happen on a rescan. Running ./syncthing-inotify -help gives a "Illegal instruction: 4" Error.

I tried doing the exact same steps on a mac running 10.8.5 and this behaviour doesn't happen (works as expected)

**Comment by calmh** [comment]
http://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10 but I'm not sure what the correct solution for our build process is.

**Comment by Zillode** [comment]
Could you try compiling syncthing-inotify yourself?
1. Download golang: https://golang.org/dl/
2. ```export GOROOT=/Users/myuser/Downloads/go```
3. Follow https://github.com/syncthing/syncthing-inotify#building-syncthing-inotify

**Comment by lichtamberg** [comment]
Compiling myself worked fine on 10.9.5.
Btw, is it necessary to run ruby cross-compile.rb before building it the first time on OSX?

**Comment by Zillode** [comment]
Interesting...
No, it's not required. I only use it to build for non-native platforms.

**Comment by Zillode** [comment]
@lichtamberg could you try again with syncthing-inotify [v0.7](https://github.com/syncthing/syncthing-inotify/releases/tag/v0.7)?
