### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by alexforencich** [syncthing/syncthing-inotify#75]
When I try to start syncthing-inotify, I get the following error message:

    [WARNING] 17:46:33 Failed to install inotify handlers permission denied

and the syncthing interface reports

    2015-07-27 17:46:33: [Inotify] Failed to install inotify handler for Projects

I get no errors with inotifywatch

    $ inotifywatch -vr Projects/Establishing watches...
    Setting up watch(es) on Projects/
    OK, Projects/ is now being watched.
    Total of 31869 watches.
    Finished establishing watches, now collecting statistics.

I also cranked up the inotify watch limit to 131072.  The directory contains about 300k files.  Could syncthing-inotify be attempting to watch each individual file instead of just the folders?  If so, this is a serious bug.  

I ran chown -R on the folder to make sure that I own everything.  However, I cannot seem to get syncthing-inotify to work.  Any ideas on what might be going on here?

**Comment by capi** [comment]
Just to be sure: the user that is running `syncthing-inotify` has filesytem permissions for the folder to watch?

**Comment by alexforencich** [comment]
Yes.  The directory is chown'd to the same user that syncthing-inotify is run under.  It might be a good idea to print out specifically what path is causing the failure within syncthing-inotify to get a better handle on what might be going on.

**Comment by Zillode** [comment]
We rely on the [rjeczalik notify upstream package](https://github.com/rjeczalik/notify). Given the Go-specific constraints, I don't think there is a better solution at the moment. Please consider contributing to notify or fsnotify: https://github.com/rjeczalik/notify/blob/master/watcher_inotify.go and https://github.com/go-fsnotify/fsnotify/issues/79.

**Comment by capi** [comment]
@alexforencich because I had a similar issue once: all the directories leading up to the to-be-watched directories are accessible (ugo+x, whatever applies) for this user? The path it uses should be the same as specified in the `syncthing` configuration.

**Comment by alexforencich** [comment]
Interesting.  I just tried chmod -R a+rX * and now it seems to be working.  There must have been a directory in there somewhere with screwed up permissions.  I think it would be a good idea to print out what path is causing the problem to make debugging this sort of thing easier.

**Comment by Zillode** [comment]
Fixed / dup of #53
