### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by xl4m3rx** [syncthing/syncthing-inotify#78]
Hi, i have run the current version of syncthing-inotify on my nas (Linux NSA325-v2 2.6.31.8 #2 Fri May 15 12:20:01 CST 2015 armv5tel GNU/Linux) and it result in Illegal instruction (core dumped).

What must i do?
thanks.

CoreDump was generated by `./syncthing-inotify'.
Program terminated with signal 4, Illegal instruction.
#0  0x00056c60 in ?? ()

**Comment by AudriusButkevicius** [comment]
Best bet is compiling yourself.
There is also some specific NAS which needs modifications to the Go runtime code to be able to work. Check the forums if that's not the model you have.
