### ISSUE TITLE
Poor OSX Support

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing-inotify#8]
See https://github.com/howeyc/fsnotify/issues/54

**Comment by SjonHortensius** [comment]
Fyi; the same thing happened to me on linux, on a directory containing 36k subdirs. Increasing max_user_watches works as well

**Comment by Zillode** [comment]
Thanks @SjonHortensius, I updated the README.
Also, https://github.com/rjeczalik/notify looks promising

**Comment by Zillode** [comment]
Should be fixed in upstream and our beta release. Please try it out, thanks!
