### ISSUE TITLE
Not verifying internet shortcuts filename.url in Windows

### ISSUE THREAD

**Issue by sestaricruz** [syncthing/syncthing-inotify#92]
When you delete a internet shortcut file .url in Windows at a time it notify ST and works fine, but when you delete a multiple selection with a shortcut file included, it apparently notify ST, show the internet shortcut file name being notified at inotify console log window but ST only verify the other files, leaving a extra numer of 1+ at ST interface and do not make the exclusion of the shortcut file at the devices that are synced, it becomes a king of ghost file, it only vanishes and sync at the file number ST web interface when you restart syncthing.
(Sorry about bad English language, English language newbie here)

**Comment by sestaricruz** [comment]
![captura de tela 2016-02-11 22 23 28](https://cloud.githubusercontent.com/assets/17188168/12996427/6b5f350c-d10e-11e5-909f-b008a44a24a1.png)

**Comment by sestaricruz** [comment]
This issue is only happening when you make a local exclusion at your Windows explorer window, remote multiple selection exclusions with shortcut files included coming from other devices like a android phone are reflecting at the remote and local file count fine

**Comment by Zillode** [comment]
@sestaricruz  could you try again with syncthing-inotify [v0.7](https://github.com/syncthing/syncthing-inotify/releases/tag/v0.7)?
