### ISSUE TITLE
RFE: delay notifying syncthing of files that are still being written to

### ISSUE THREAD

**Issue by chiastic-security** [syncthing/syncthing-inotify#95]
I've noticed that when I run something that writes heavily to a single file, syncthing-inotify kicks in constantly, and this causes syncthing to sync the file over and over again. This is so resource-intensive that I end up turning off syncthing entirely, and then I have to remember to turn it back on again.

Obviously if you want perfect realtime updates, then this is the right way to do it, but it's very expensive, and for lots of use cases it's fine to back off a bit and wait till the file has finished being written to, or at least only notify syncthing of the change every so often, so that it doesn't get spammed. Essentially this gentler approach does the same thing that a write cache does for a hard disk, where typically it's better to delay writes for a few seconds in order to improve performance.

Could we have something like this in syncthing-inotify? A suggested implementation is to delay notifying for all file writes (like a write cache). When a file is changed, add to the cache, and evict and notify syncthing after a (configurable) delay of maybe 15 seconds or so.

**Comment by Zillode** [comment]
This is how it works. The current timeout is rather fast, i.e. [500 ms](https://github.com/syncthing/syncthing-inotify/blob/6da7f5f227bc2ac32202aa01fe4201773daf5717/syncwatcher.go#L116).

**Comment by AudriusButkevicius** [comment]
What if it never stops changing though.

**Comment by Zillode** [comment]
There is another timeout to cover that case.

**Comment by plouj** [comment]
Well, right now we keep track of when we got the latest event for a
particular file (
https://github.com/syncthing/syncthing-inotify/blob/c612496d6e86c864a1dddbb84c3d11552b8fb9e4/syncwatcher.go#L686),
but this is only used to prune files that have been in progress for too
long. We could make use of this data to not notify ST about changes to
files that have changed more recently than the 500 ms aggregate timeout.

**Comment by Zillode** [comment]
What would be an appropriate timeout value for this?

**Comment by chiastic-security** [comment]
I'd incline to something fairly high. Linux by default uses 5 seconds as a timeout before it flushes dirty cache to disk, and that's for locally attached storage where the cost of writing is quite low. For pushing over a network, it's an even higher cost.

But I think the more important thing is to make it a user-configurable parameter (without needing to recompile).

**Comment by ultra-sonic** [comment]
+1 for this...having issues when syncing my images from a remote
renderfarm..it seems that the images get synced while the renderer is still
writing to the file. Could that be? Is there way of preventing such a sync
other than with this RFE?

**Comment by chiastic-security** [comment]
This aside, there are a couple of things you could try. If you can get the renderer to write the image with a different filename that ends in '.partial' or something, and then rename it at the end to remove the suffix, then you can exclude those '.partial' files from the sync process.

If not, you could lower the CPU and I/O priorities of the syncthing process. That at least will stop it slowing the rendering job down.

**Comment by ultra-sonic** [comment]
thx James! the ".partial" suffix sounds good to me...

**Comment by Zillode** [comment]
:+1:

**Comment by chiastic-security** [comment]
Nice! Thank you.
