### ISSUE TITLE
syncthing-inotify fails with excluded fuse mounts b/c .stignore is evaluated too late

### ISSUE THREAD

**Issue by mnagel** [syncthing/syncthing-inotify#98]
In https://github.com/syncthing/syncthing-inotify/blob/a2d07bcdc423624a05e27c698ad80f68243762ba/syncwatcher.go#L429 a recursive watch **including ALL sub-items** is installed for the folder.

Then, **later** in https://github.com/syncthing/syncthing-inotify/blob/a2d07bcdc423624a05e27c698ad80f68243762ba/syncwatcher.go#L451 the `.stignore` effects are considered.

This makes `syncthing-inotify` break if there are some files/folders where inotify does not work even when these files are explicitly excluded via `.stignore`.
This happened to me when trying to put my whole `$HOME` into syncthing and exclude `.gvfs` which is a FUSE mount where inotify does not work.

The proper solution (imho) would be to support excluding certain paths in the call to `notify.Watch` and forward the `.stignore` patterns there.

**Comment by Zillode** [comment]
Related to https://github.com/rjeczalik/notify/issues/79
