### ISSUE TITLE
Support user-defined accumulation intervals

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing-inotify#99]
I would love to have an option that accumulates changes for a specified time before sending it to syncthing. Currently if there is a file that is often modified by a program, syncthing is constantly scanning it which uses lots of resources. This would be like standard interval scans by syncthing, but with the benefit added by syncthing-inotify that only changed files/dirs are scanned.

**Comment by ultra-sonic** [comment]
isn't that the same as the "cooldown" thing that was discussed (and
solved?) in another issue?

**Comment by imsodin** [comment]
This is indeed the same as the initial request in issue #95 which was closed after the commit [Wait for frequently modified files to settle.](https://github.com/plouj/syncthing-inotify/commit/a2d07bcdc423624a05e27c698ad80f68243762ba). As far as I understand this should fix the problem with one file that is often written to.

However I still think a user configurable time to wait before sending any aggregated changes to syncthing would be very useful for reducing load. I would not mind at all to have a delay of e.g. 5min.

Regarding the above commit: It is after 0.6.8 so I tried to compile it myself. However when following the build explanation at "go get" I get the error
```
# github.com/zillode/notify
../../zillode/notify/node.go:73: undefined: fmt in fmt.Errorf
```
I am using debian testing with go version go1.6 linux/amd64. I hope it is appropriate to ask this here, otherwise I would appreciate any help per email.

**Comment by Zillode** [comment]
>However I still think a user configurable time to wait before sending any aggregated changes to syncthing would be very useful for reducing load. I would not mind at all to have a delay of e.g. 5min.

PR is welcome:)

>undefined: fmt in fmt.Errorf

Fixed, please try `go get` again.

**Comment by imsodin** [comment]
> > However I still think a user configurable time to wait before sending any aggregated changes to syncthing would be very useful for reducing load. I would not mind at all to have a delay of e.g. 5min.
> 
> PR is welcome:)

Apart from some python and bash scripting knowledge, my programming skills are practically nonexistant and I have never had any contact with go before - but maybe I find the time and interest to do it :)
As the fixes in the recent commits seem to be effective for the problem that triggered me to write this issue, the motivation may be not strong enough.

>> undefined: fmt in fmt.Errorf

>Fixed, please try go get again.

Now it works, thanks for your help.

**Comment by Zillode** [comment]
Fixed by https://github.com/syncthing/syncthing-inotify/commit/90500125623232ff71b5e55e1c3ed1cc38b190e8
